-- // seed auth tables
-- Migration SQL that makes the change goes here.

INSERT INTO `core__entity_name_rule` VALUES (NULL,'anal',1,0,now(),now());
INSERT INTO `core__entity_name_rule` VALUES (NULL,'anus',1,0,now(),now());
INSERT INTO `core__entity_name_rule` VALUES (NULL,'arse',1,0,now(),now());
INSERT INTO `core__entity_name_rule` VALUES (NULL,'ass',1,0,now(),now());
INSERT INTO `core__entity_name_rule` VALUES (NULL,'ballsack',1,0,now(),now());
INSERT INTO `core__entity_name_rule` VALUES (NULL,'balls',1,0,now(),now());
INSERT INTO `core__entity_name_rule` VALUES (NULL,'bastard',1,0,now(),now());
INSERT INTO `core__entity_name_rule` VALUES (NULL,'bitch',1,0,now(),now());
INSERT INTO `core__entity_name_rule` VALUES (NULL,'biatch',1,0,now(),now());
INSERT INTO `core__entity_name_rule` VALUES (NULL,'bloody',1,0,now(),now());
INSERT INTO `core__entity_name_rule` VALUES (NULL,'blowjob',1,0,now(),now());
INSERT INTO `core__entity_name_rule` VALUES (NULL,'blow job',1,0,now(),now());
INSERT INTO `core__entity_name_rule` VALUES (NULL,'bollock',1,0,now(),now());
INSERT INTO `core__entity_name_rule` VALUES (NULL,'bollok',1,0,now(),now());
INSERT INTO `core__entity_name_rule` VALUES (NULL,'boner',1,0,now(),now());
INSERT INTO `core__entity_name_rule` VALUES (NULL,'boob',1,0,now(),now());
INSERT INTO `core__entity_name_rule` VALUES (NULL,'bugger',1,0,now(),now());
INSERT INTO `core__entity_name_rule` VALUES (NULL,'bum',1,0,now(),now());
INSERT INTO `core__entity_name_rule` VALUES (NULL,'butt',1,0,now(),now());
INSERT INTO `core__entity_name_rule` VALUES (NULL,'buttplug',1,0,now(),now());
INSERT INTO `core__entity_name_rule` VALUES (NULL,'clitoris',1,0,now(),now());
INSERT INTO `core__entity_name_rule` VALUES (NULL,'cock',1,0,now(),now());
INSERT INTO `core__entity_name_rule` VALUES (NULL,'coon',1,0,now(),now());
INSERT INTO `core__entity_name_rule` VALUES (NULL,'crap',1,0,now(),now());
INSERT INTO `core__entity_name_rule` VALUES (NULL,'cunt',1,0,now(),now());
INSERT INTO `core__entity_name_rule` VALUES (NULL,'damn',1,0,now(),now());
INSERT INTO `core__entity_name_rule` VALUES (NULL,'dick',1,0,now(),now());
INSERT INTO `core__entity_name_rule` VALUES (NULL,'dildo',1,0,now(),now());
INSERT INTO `core__entity_name_rule` VALUES (NULL,'dyke',1,0,now(),now());
INSERT INTO `core__entity_name_rule` VALUES (NULL,'fag',1,0,now(),now());
INSERT INTO `core__entity_name_rule` VALUES (NULL,'feck',1,0,now(),now());
INSERT INTO `core__entity_name_rule` VALUES (NULL,'fellate',1,0,now(),now());
INSERT INTO `core__entity_name_rule` VALUES (NULL,'fellatio',1,0,now(),now());
INSERT INTO `core__entity_name_rule` VALUES (NULL,'felching',1,0,now(),now());
INSERT INTO `core__entity_name_rule` VALUES (NULL,'fuck',1,0,now(),now());
INSERT INTO `core__entity_name_rule` VALUES (NULL,'f u c k',1,0,now(),now());
INSERT INTO `core__entity_name_rule` VALUES (NULL,'fudgepacker',1,0,now(),now());
INSERT INTO `core__entity_name_rule` VALUES (NULL,'fudge packer',1,0,now(),now());
INSERT INTO `core__entity_name_rule` VALUES (NULL,'flange',1,0,now(),now());
INSERT INTO `core__entity_name_rule` VALUES (NULL,'Goddamn',1,0,now(),now());
INSERT INTO `core__entity_name_rule` VALUES (NULL,'God damn',1,0,now(),now());
INSERT INTO `core__entity_name_rule` VALUES (NULL,'hell',1,0,now(),now());
INSERT INTO `core__entity_name_rule` VALUES (NULL,'homo',1,0,now(),now());
INSERT INTO `core__entity_name_rule` VALUES (NULL,'jerk',1,0,now(),now());
INSERT INTO `core__entity_name_rule` VALUES (NULL,'jizz',1,0,now(),now());
INSERT INTO `core__entity_name_rule` VALUES (NULL,'knobend',1,0,now(),now());
INSERT INTO `core__entity_name_rule` VALUES (NULL,'knob end',1,0,now(),now());
INSERT INTO `core__entity_name_rule` VALUES (NULL,'labia',1,0,now(),now());
INSERT INTO `core__entity_name_rule` VALUES (NULL,'lmao',1,0,now(),now());
INSERT INTO `core__entity_name_rule` VALUES (NULL,'lmfao',1,0,now(),now());
INSERT INTO `core__entity_name_rule` VALUES (NULL,'muff',1,0,now(),now());
INSERT INTO `core__entity_name_rule` VALUES (NULL,'nigger',1,0,now(),now());
INSERT INTO `core__entity_name_rule` VALUES (NULL,'nigga',1,0,now(),now());
INSERT INTO `core__entity_name_rule` VALUES (NULL,'omg',1,0,now(),now());
INSERT INTO `core__entity_name_rule` VALUES (NULL,'penis',1,0,now(),now());
INSERT INTO `core__entity_name_rule` VALUES (NULL,'piss',1,0,now(),now());
INSERT INTO `core__entity_name_rule` VALUES (NULL,'poop',1,0,now(),now());
INSERT INTO `core__entity_name_rule` VALUES (NULL,'prick',1,0,now(),now());
INSERT INTO `core__entity_name_rule` VALUES (NULL,'pube',1,0,now(),now());
INSERT INTO `core__entity_name_rule` VALUES (NULL,'pussy',1,0,now(),now());
INSERT INTO `core__entity_name_rule` VALUES (NULL,'queer',1,0,now(),now());
INSERT INTO `core__entity_name_rule` VALUES (NULL,'scrotum',1,0,now(),now());
INSERT INTO `core__entity_name_rule` VALUES (NULL,'sex',1,0,now(),now());
INSERT INTO `core__entity_name_rule` VALUES (NULL,'shit',1,0,now(),now());
INSERT INTO `core__entity_name_rule` VALUES (NULL,'s hit',1,0,now(),now());
INSERT INTO `core__entity_name_rule` VALUES (NULL,'sh1t',1,0,now(),now());
INSERT INTO `core__entity_name_rule` VALUES (NULL,'slut',1,0,now(),now());
INSERT INTO `core__entity_name_rule` VALUES (NULL,'smegma',1,0,now(),now());
INSERT INTO `core__entity_name_rule` VALUES (NULL,'spunk',1,0,now(),now());
INSERT INTO `core__entity_name_rule` VALUES (NULL,'tit',1,0,now(),now());
INSERT INTO `core__entity_name_rule` VALUES (NULL,'tosser',1,0,now(),now());
INSERT INTO `core__entity_name_rule` VALUES (NULL,'turd',1,0,now(),now());
INSERT INTO `core__entity_name_rule` VALUES (NULL,'twat',1,0,now(),now());
INSERT INTO `core__entity_name_rule` VALUES (NULL,'vagina',1,0,now(),now());
INSERT INTO `core__entity_name_rule` VALUES (NULL,'wank',1,0,now(),now());
INSERT INTO `core__entity_name_rule` VALUES (NULL,'whore',1,0,now(),now());
INSERT INTO `core__entity_name_rule` VALUES (NULL,'wtf',1,0,now(),now());
INSERT INTO `core__entity_name_rule` VALUES (NULL,'start',0,1,now(),now());
INSERT INTO `core__entity_name_rule` VALUES (NULL,'stop',0,1,now(),now());
INSERT INTO `core__entity_name_rule` VALUES (NULL,'begin',0,1,now(),now());
INSERT INTO `core__entity_name_rule` VALUES (NULL,'end',0,1,now(),now());
INSERT INTO `core__entity_name_rule` VALUES (NULL,'snapchat',0,1,now(),now());
INSERT INTO `core__entity_name_rule` VALUES (NULL,'instagram',0,1,now(),now());
INSERT INTO `core__entity_name_rule` VALUES (NULL,'linkedin',0,1,now(),now());
INSERT INTO `core__entity_name_rule` VALUES (NULL,'twitter',0,1,now(),now());
INSERT INTO `core__entity_name_rule` VALUES (NULL,'facebook',0,1,now(),now());
INSERT INTO `core__entity_name_rule` VALUES (NULL,'google',0,1,now(),now());
INSERT INTO `core__entity_name_rule` VALUES (NULL,'google+',0,1,now(),now());
INSERT INTO `core__entity_name_rule` VALUES (NULL,'email',0,1,now(),now());
INSERT INTO `core__entity_name_rule` VALUES (NULL,'sms',0,1,now(),now());
INSERT INTO `core__entity_name_rule` VALUES (NULL,'text',0,1,now(),now());
INSERT INTO `core__entity_name_rule` VALUES (NULL,'www',0,1,now(),now());
INSERT INTO `core__entity_name_rule` VALUES (NULL,'web',0,1,now(),now());
INSERT INTO `core__entity_name_rule` VALUES (NULL,'system',0,1,now(),now());
INSERT INTO `core__entity_name_rule` VALUES (NULL,'rpc',0,1,now(),now());
INSERT INTO `core__entity_name_rule` VALUES (NULL,'login',0,1,now(),now());
INSERT INTO `core__entity_name_rule` VALUES (NULL,'logout',0,1,now(),now());
INSERT INTO `core__entity_name_rule` VALUES (NULL,'app',0,1,now(),now());
INSERT INTO `core__entity_name_rule` VALUES (NULL,'apps',0,1,now(),now());
INSERT INTO `core__entity_name_rule` VALUES (NULL,'route',0,1,now(),now());
INSERT INTO `core__entity_name_rule` VALUES (NULL,'routes',0,1,now(),now());
INSERT INTO `core__entity_name_rule` VALUES (NULL,'admin',0,1,now(),now());
INSERT INTO `core__entity_name_rule` VALUES (NULL,'qa',0,1,now(),now());
INSERT INTO `core__entity_name_rule` VALUES (NULL,'setting',0,1,now(),now());
INSERT INTO `core__entity_name_rule` VALUES (NULL,'settings',0,1,now(),now());
INSERT INTO `core__entity_name_rule` VALUES (NULL,'docs',0,1,now(),now());
INSERT INTO `core__entity_name_rule` VALUES (NULL,'api',0,1,now(),now());
INSERT INTO `core__entity_name_rule` VALUES (NULL,'file',0,1,now(),now());
INSERT INTO `core__entity_name_rule` VALUES (NULL,'files',0,1,now(),now());
INSERT INTO `core__entity_name_rule` VALUES (NULL,'download',0,1,now(),now());
INSERT INTO `core__entity_name_rule` VALUES (NULL,'downloads',0,1,now(),now());
INSERT INTO `core__entity_name_rule` VALUES (NULL,'about',0,1,now(),now());
INSERT INTO `core__entity_name_rule` VALUES (NULL,'legal',0,1,now(),now());
INSERT INTO `core__entity_name_rule` VALUES (NULL,'terms',0,1,now(),now());
INSERT INTO `core__entity_name_rule` VALUES (NULL,'privacy',0,1,now(),now());
INSERT INTO `core__entity_name_rule` VALUES (NULL,'confirm',0,1,now(),now());
INSERT INTO `core__entity_name_rule` VALUES (NULL,'alert',0,1,now(),now());
INSERT INTO `core__entity_name_rule` VALUES (NULL,'alerts',0,1,now(),now());
INSERT INTO `core__entity_name_rule` VALUES (NULL,'threat',0,1,now(),now());
INSERT INTO `core__entity_name_rule` VALUES (NULL,'threats',0,1,now(),now());
INSERT INTO `core__entity_name_rule` VALUES (NULL,'asset',0,1,now(),now());
INSERT INTO `core__entity_name_rule` VALUES (NULL,'assets',0,1,now(),now());
INSERT INTO `core__entity_name_rule` VALUES (NULL,'promo',0,1,now(),now());
INSERT INTO `core__entity_name_rule` VALUES (NULL,'promos',0,1,now(),now());
INSERT INTO `core__entity_name_rule` VALUES (NULL,'partner',0,1,now(),now());
INSERT INTO `core__entity_name_rule` VALUES (NULL,'partners',0,1,now(),now());
INSERT INTO `core__entity_name_rule` VALUES (NULL,'account',0,1,now(),now());
INSERT INTO `core__entity_name_rule` VALUES (NULL,'user',0,1,now(),now());
INSERT INTO `core__entity_name_rule` VALUES (NULL,'jdoe',0,1,now(),now());
INSERT INTO `core__entity_name_rule` VALUES (NULL,'johndoe',0,1,now(),now());
INSERT INTO `core__entity_name_rule` VALUES (NULL,'janedoe',0,1,now(),now());
INSERT INTO `core__entity_name_rule` VALUES (NULL,'john.doe',0,1,now(),now());
INSERT INTO `core__entity_name_rule` VALUES (NULL,'jane.doe',0,1,now(),now());
INSERT INTO `core__entity_name_rule` VALUES (NULL,'service',0,1,now(),now());
INSERT INTO `core__entity_name_rule` VALUES (NULL,'services',0,1,now(),now());
-- INSERT INTO `core__entity_name_rule` VALUES (NULL,'sharif',0,1,now(),now());
-- INSERT INTO `core__entity_name_rule` VALUES (NULL,'violet',0,1,now(),now());
-- INSERT INTO `core__entity_name_rule` VALUES (NULL,'chris',0,1,now(),now());
-- INSERT INTO `core__entity_name_rule` VALUES (NULL,'christopher',0,1,now(),now());
-- INSERT INTO `core__entity_name_rule` VALUES (NULL,'aiden',0,1,now(),now());


-- //@UNDO
-- SQL to undo the change goes here.
delete from core__entity_name_rule;
