package com.linuxtek.kona.app.sales.entity;

import java.math.BigDecimal;
import java.util.Date;

public class KBaseCart implements KCart {

	private static final long serialVersionUID = 1L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart.id
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart.app_id
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private Long appId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart.user_id
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart.account_id
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private Long accountId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart.currency_id
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private Long currencyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart.invoice_id
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private Long invoiceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart.session_id
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private String sessionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart.access_token
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private String accessToken;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart.hostname
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private String hostname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart.browser
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private String browser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart.latitude
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private Double latitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart.longitude
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private Double longitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart.description
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart.notes
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private String notes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart.default_card_last4
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private String defaultCardLast4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart.subtotal
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private BigDecimal subtotal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart.discount
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private BigDecimal discount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart.shipping
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private BigDecimal shipping;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart.tax
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private BigDecimal tax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart.total
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private BigDecimal total;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart.checked_out
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private boolean checkedOut;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart.invoiced
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private boolean invoiced;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart.expired
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private boolean expired;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart.created_date
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private Date createdDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart.expired_date
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private Date expiredDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart.checked_out_date
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private Date checkedOutDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart.invoiced_date
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private Date invoicedDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart.last_updated
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private Date lastUpdated;

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCart#getId()
	 */
    @Override
	public Long getId() {
        return id;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCart#setId(java.lang.Long)
	 */
    @Override
	public void setId(Long id) {
        this.id = id;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCart#getAppId()
	 */
    @Override
	public Long getAppId() {
        return appId;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCart#setAppId(java.lang.Long)
	 */
    @Override
	public void setAppId(Long appId) {
        this.appId = appId;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCart#getUserId()
	 */
    @Override
	public Long getUserId() {
        return userId;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCart#setUserId(java.lang.Long)
	 */
    @Override
	public void setUserId(Long userId) {
        this.userId = userId;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCart#getAccountId()
	 */
    @Override
	public Long getAccountId() {
        return accountId;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCart#setAccountId(java.lang.Long)
	 */
    @Override
	public void setAccountId(Long accountId) {
        this.accountId = accountId;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCart#getCurrencyId()
	 */
    @Override
	public Long getCurrencyId() {
        return currencyId;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCart#setCurrencyId(java.lang.Long)
	 */
    @Override
	public void setCurrencyId(Long currencyId) {
        this.currencyId = currencyId;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCart#getInvoiceId()
	 */
    @Override
	public Long getInvoiceId() {
        return invoiceId;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCart#setInvoiceId(java.lang.Long)
	 */
    @Override
	public void setInvoiceId(Long invoiceId) {
        this.invoiceId = invoiceId;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCart#getSessionId()
	 */
    @Override
	public String getSessionId() {
        return sessionId;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCart#setSessionId(java.lang.String)
	 */
    @Override
	public void setSessionId(String sessionId) {
        this.sessionId = sessionId == null ? null : sessionId.trim();
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCart#getAccessToken()
	 */
    @Override
	public String getAccessToken() {
        return accessToken;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCart#setAccessToken(java.lang.String)
	 */
    @Override
	public void setAccessToken(String accessToken) {
        this.accessToken = accessToken == null ? null : accessToken.trim();
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCart#getHostname()
	 */
    @Override
	public String getHostname() {
        return hostname;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCart#setHostname(java.lang.String)
	 */
    @Override
	public void setHostname(String hostname) {
        this.hostname = hostname == null ? null : hostname.trim();
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCart#getBrowser()
	 */
    @Override
	public String getBrowser() {
        return browser;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCart#setBrowser(java.lang.String)
	 */
    @Override
	public void setBrowser(String browser) {
        this.browser = browser == null ? null : browser.trim();
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCart#getLatitude()
	 */
    @Override
	public Double getLatitude() {
        return latitude;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCart#setLatitude(java.lang.Double)
	 */
    @Override
	public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCart#getLongitude()
	 */
    @Override
	public Double getLongitude() {
        return longitude;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCart#setLongitude(java.lang.Double)
	 */
    @Override
	public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCart#getDescription()
	 */
    @Override
	public String getDescription() {
        return description;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCart#setDescription(java.lang.String)
	 */
    @Override
	public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCart#getNotes()
	 */
    @Override
	public String getNotes() {
        return notes;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCart#setNotes(java.lang.String)
	 */
    @Override
	public void setNotes(String notes) {
        this.notes = notes == null ? null : notes.trim();
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCart#getDefaultCardLast4()
	 */
    @Override
	public String getDefaultCardLast4() {
        return defaultCardLast4;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCart#setDefaultCardLast4(java.lang.String)
	 */
    @Override
	public void setDefaultCardLast4(String defaultCardLast4) {
        this.defaultCardLast4 = defaultCardLast4 == null ? null : defaultCardLast4.trim();
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCart#getSubtotal()
	 */
    @Override
	public BigDecimal getSubtotal() {
        return subtotal;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCart#setSubtotal(java.math.BigDecimal)
	 */
    @Override
	public void setSubtotal(BigDecimal subtotal) {
        this.subtotal = subtotal;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCart#getDiscount()
	 */
    @Override
	public BigDecimal getDiscount() {
        return discount;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCart#setDiscount(java.math.BigDecimal)
	 */
    @Override
	public void setDiscount(BigDecimal discount) {
        this.discount = discount;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCart#getShipping()
	 */
    @Override
	public BigDecimal getShipping() {
        return shipping;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCart#setShipping(java.math.BigDecimal)
	 */
    @Override
	public void setShipping(BigDecimal shipping) {
        this.shipping = shipping;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCart#getTax()
	 */
    @Override
	public BigDecimal getTax() {
        return tax;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCart#setTax(java.math.BigDecimal)
	 */
    @Override
	public void setTax(BigDecimal tax) {
        this.tax = tax;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCart#getTotal()
	 */
    @Override
	public BigDecimal getTotal() {
        return total;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCart#setTotal(java.math.BigDecimal)
	 */
    @Override
	public void setTotal(BigDecimal total) {
        this.total = total;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCart#isCheckedOut()
	 */
    @Override
	public boolean isCheckedOut() {
        return checkedOut;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCart#setCheckedOut(boolean)
	 */
    @Override
	public void setCheckedOut(boolean checkedOut) {
        this.checkedOut = checkedOut;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCart#isInvoiced()
	 */
    @Override
	public boolean isInvoiced() {
        return invoiced;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCart#setInvoiced(boolean)
	 */
    @Override
	public void setInvoiced(boolean invoiced) {
        this.invoiced = invoiced;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCart#isExpired()
	 */
    @Override
	public boolean isExpired() {
        return expired;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCart#setExpired(boolean)
	 */
    @Override
	public void setExpired(boolean expired) {
        this.expired = expired;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCart#getCreatedDate()
	 */
    @Override
	public Date getCreatedDate() {
        return createdDate;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCart#setCreatedDate(java.util.Date)
	 */
    @Override
	public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCart#getExpiredDate()
	 */
    @Override
	public Date getExpiredDate() {
        return expiredDate;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCart#setExpiredDate(java.util.Date)
	 */
    @Override
	public void setExpiredDate(Date expiredDate) {
        this.expiredDate = expiredDate;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCart#getCheckedOutDate()
	 */
    @Override
	public Date getCheckedOutDate() {
        return checkedOutDate;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCart#setCheckedOutDate(java.util.Date)
	 */
    @Override
	public void setCheckedOutDate(Date checkedOutDate) {
        this.checkedOutDate = checkedOutDate;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCart#getInvoicedDate()
	 */
    @Override
	public Date getInvoicedDate() {
        return invoicedDate;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCart#setInvoicedDate(java.util.Date)
	 */
    @Override
	public void setInvoicedDate(Date invoicedDate) {
        this.invoicedDate = invoicedDate;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCart#getLastUpdated()
	 */
    @Override
	public Date getLastUpdated() {
        return lastUpdated;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCart#setLastUpdated(java.util.Date)
	 */
    @Override
	public void setLastUpdated(Date lastUpdated) {
        this.lastUpdated = lastUpdated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", appId=").append(appId);
        sb.append(", userId=").append(userId);
        sb.append(", accountId=").append(accountId);
        sb.append(", currencyId=").append(currencyId);
        sb.append(", invoiceId=").append(invoiceId);
        sb.append(", sessionId=").append(sessionId);
        sb.append(", accessToken=").append(accessToken);
        sb.append(", hostname=").append(hostname);
        sb.append(", browser=").append(browser);
        sb.append(", latitude=").append(latitude);
        sb.append(", longitude=").append(longitude);
        sb.append(", description=").append(description);
        sb.append(", notes=").append(notes);
        sb.append(", defaultCardLast4=").append(defaultCardLast4);
        sb.append(", subtotal=").append(subtotal);
        sb.append(", discount=").append(discount);
        sb.append(", shipping=").append(shipping);
        sb.append(", tax=").append(tax);
        sb.append(", total=").append(total);
        sb.append(", checkedOut=").append(checkedOut);
        sb.append(", invoiced=").append(invoiced);
        sb.append(", expired=").append(expired);
        sb.append(", createdDate=").append(createdDate);
        sb.append(", expiredDate=").append(expiredDate);
        sb.append(", checkedOutDate=").append(checkedOutDate);
        sb.append(", invoicedDate=").append(invoicedDate);
        sb.append(", lastUpdated=").append(lastUpdated);
        sb.append("]");
        return sb.toString();
    }
}
