package com.linuxtek.kona.app.sales.entity;

import java.util.Date;

public class KBaseSalesLead implements KSalesLead {

	private static final long serialVersionUID = 1L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_lead.id
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_lead.uid
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private String uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_lead.app_id
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private Long appId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_lead.ref_app_id
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private Long refAppId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_lead.first_name
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private String firstName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_lead.last_name
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private String lastName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_lead.phone
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_lead.email
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_lead.mobile_number
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private String mobileNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_lead.comment
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private String comment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_lead.twitterUsername
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private String twitterusername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_lead.facebookUsername
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private String facebookusername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_lead.referred_by_user_id
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private Long referredByUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_lead.campaign_id
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private Long campaignId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_lead.channel
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private String channel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_lead.interests
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private String interests;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_lead.hostname
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private String hostname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_lead.browser
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private String browser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_lead.created_date
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private Date createdDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_lead.last_updated
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private Date updatedDate;

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KSalesLead#getId()
	 */
    @Override
	public Long getId() {
        return id;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KSalesLead#setId(java.lang.Long)
	 */
    @Override
	public void setId(Long id) {
        this.id = id;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KSalesLead#getUid()
	 */
    @Override
	public String getUid() {
        return uid;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KSalesLead#setUid(java.lang.String)
	 */
    @Override
	public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KSalesLead#getAppId()
	 */
    @Override
	public Long getAppId() {
        return appId;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KSalesLead#setAppId(java.lang.Long)
	 */
    @Override
	public void setAppId(Long appId) {
        this.appId = appId;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KSalesLead#getRefAppId()
	 */
    @Override
	public Long getRefAppId() {
        return refAppId;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KSalesLead#setRefAppId(java.lang.Long)
	 */
    @Override
	public void setRefAppId(Long refAppId) {
        this.refAppId = refAppId;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KSalesLead#getFirstName()
	 */
    @Override
	public String getFirstName() {
        return firstName;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KSalesLead#setFirstName(java.lang.String)
	 */
    @Override
	public void setFirstName(String firstName) {
        this.firstName = firstName == null ? null : firstName.trim();
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KSalesLead#getLastName()
	 */
    @Override
	public String getLastName() {
        return lastName;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KSalesLead#setLastName(java.lang.String)
	 */
    @Override
	public void setLastName(String lastName) {
        this.lastName = lastName == null ? null : lastName.trim();
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KSalesLead#getPhone()
	 */
    @Override
	public String getPhone() {
        return phone;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KSalesLead#setPhone(java.lang.String)
	 */
    @Override
	public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KSalesLead#getEmail()
	 */
    @Override
	public String getEmail() {
        return email;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KSalesLead#setEmail(java.lang.String)
	 */
    @Override
	public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KSalesLead#getMobileNumber()
	 */
    @Override
	public String getMobileNumber() {
        return mobileNumber;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KSalesLead#setMobileNumber(java.lang.String)
	 */
    @Override
	public void setMobileNumber(String mobileNumber) {
        this.mobileNumber = mobileNumber == null ? null : mobileNumber.trim();
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KSalesLead#getComment()
	 */
    @Override
	public String getComment() {
        return comment;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KSalesLead#setComment(java.lang.String)
	 */
    @Override
	public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KSalesLead#getTwitterusername()
	 */
    @Override
	public String getTwitterusername() {
        return twitterusername;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KSalesLead#setTwitterusername(java.lang.String)
	 */
    @Override
	public void setTwitterusername(String twitterusername) {
        this.twitterusername = twitterusername == null ? null : twitterusername.trim();
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KSalesLead#getFacebookusername()
	 */
    @Override
	public String getFacebookusername() {
        return facebookusername;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KSalesLead#setFacebookusername(java.lang.String)
	 */
    @Override
	public void setFacebookusername(String facebookusername) {
        this.facebookusername = facebookusername == null ? null : facebookusername.trim();
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KSalesLead#getReferredByUserId()
	 */
    @Override
	public Long getReferredByUserId() {
        return referredByUserId;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KSalesLead#setReferredByUserId(java.lang.Long)
	 */
    @Override
	public void setReferredByUserId(Long referredByUserId) {
        this.referredByUserId = referredByUserId;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KSalesLead#getCampaignId()
	 */
    @Override
	public Long getCampaignId() {
        return campaignId;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KSalesLead#setCampaignId(java.lang.Long)
	 */
    @Override
	public void setCampaignId(Long campaignId) {
        this.campaignId = campaignId;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KSalesLead#getChannel()
	 */
    @Override
	public String getChannel() {
        return channel;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KSalesLead#setChannel(java.lang.String)
	 */
    @Override
	public void setChannel(String channel) {
        this.channel = channel == null ? null : channel.trim();
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KSalesLead#getInterests()
	 */
    @Override
	public String getInterests() {
        return interests;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KSalesLead#setInterests(java.lang.String)
	 */
    @Override
	public void setInterests(String interests) {
        this.interests = interests == null ? null : interests.trim();
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KSalesLead#getHostname()
	 */
    @Override
	public String getHostname() {
        return hostname;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KSalesLead#setHostname(java.lang.String)
	 */
    @Override
	public void setHostname(String hostname) {
        this.hostname = hostname == null ? null : hostname.trim();
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KSalesLead#getBrowser()
	 */
    @Override
	public String getBrowser() {
        return browser;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KSalesLead#setBrowser(java.lang.String)
	 */
    @Override
	public void setBrowser(String browser) {
        this.browser = browser == null ? null : browser.trim();
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KSalesLead#getCreatedDate()
	 */
    @Override
	public Date getCreatedDate() {
        return createdDate;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KSalesLead#setCreatedDate(java.util.Date)
	 */
    @Override
	public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KSalesLead#getUpdatedDate()
	 */
    @Override
	public Date getUpdatedDate() {
        return updatedDate;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KSalesLead#setUpdatedDate(java.util.Date)
	 */
    @Override
	public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_lead
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", uid=").append(uid);
        sb.append(", appId=").append(appId);
        sb.append(", refAppId=").append(refAppId);
        sb.append(", firstName=").append(firstName);
        sb.append(", lastName=").append(lastName);
        sb.append(", phone=").append(phone);
        sb.append(", email=").append(email);
        sb.append(", mobileNumber=").append(mobileNumber);
        sb.append(", comment=").append(comment);
        sb.append(", twitterusername=").append(twitterusername);
        sb.append(", facebookusername=").append(facebookusername);
        sb.append(", referredByUserId=").append(referredByUserId);
        sb.append(", campaignId=").append(campaignId);
        sb.append(", channel=").append(channel);
        sb.append(", interests=").append(interests);
        sb.append(", hostname=").append(hostname);
        sb.append(", browser=").append(browser);
        sb.append(", createdDate=").append(createdDate);
        sb.append(", updatedDate=").append(updatedDate);
        sb.append("]");
        return sb.toString();
    }
}
