package com.linuxtek.kona.app.sales.entity;

import java.util.Date;

public class KBaseCampaignChannel implements KCampaignChannel {
   
	private static final long serialVersionUID = 1L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column campaign_channel.id
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column campaign_channel.uid
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private String uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column campaign_channel.campaign_id
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private Long campaignId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column campaign_channel.type_id
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private Long typeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column campaign_channel.name
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column campaign_channel.keyword
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private String keyword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column campaign_channel.sms_number
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private String smsNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column campaign_channel.url_path
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private String urlPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column campaign_channel.facebook_tracking_id
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private String facebookTrackingId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column campaign_channel.google_tracking_id
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private String googleTrackingId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column campaign_channel.enabled
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private boolean enabled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column campaign_channel.title
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column campaign_channel.image_url
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private String imageUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column campaign_channel.main_content
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private String mainContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column campaign_channel.conversion_content
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private String conversionContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column campaign_channel.created_date
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private Date createdDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column campaign_channel.start_date
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private Date startDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column campaign_channel.end_date
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private Date endDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column campaign_channel.last_updated
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private Date lastUpdated;

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCampaignChannel#getId()
	 */
    @Override
	public Long getId() {
        return id;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCampaignChannel#setId(java.lang.Long)
	 */
    @Override
	public void setId(Long id) {
        this.id = id;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCampaignChannel#getUid()
	 */
    @Override
	public String getUid() {
        return uid;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCampaignChannel#setUid(java.lang.String)
	 */
    @Override
	public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCampaignChannel#getCampaignId()
	 */
    @Override
	public Long getCampaignId() {
        return campaignId;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCampaignChannel#setCampaignId(java.lang.Long)
	 */
    @Override
	public void setCampaignId(Long campaignId) {
        this.campaignId = campaignId;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCampaignChannel#getTypeId()
	 */
    @Override
	public Long getTypeId() {
        return typeId;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCampaignChannel#setTypeId(java.lang.Long)
	 */
    @Override
	public void setTypeId(Long typeId) {
        this.typeId = typeId;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCampaignChannel#getName()
	 */
    @Override
	public String getName() {
        return name;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCampaignChannel#setName(java.lang.String)
	 */
    @Override
	public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCampaignChannel#getKeyword()
	 */
    @Override
	public String getKeyword() {
        return keyword;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCampaignChannel#setKeyword(java.lang.String)
	 */
    @Override
	public void setKeyword(String keyword) {
        this.keyword = keyword == null ? null : keyword.trim();
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCampaignChannel#getSmsNumber()
	 */
    @Override
	public String getSmsNumber() {
        return smsNumber;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCampaignChannel#setSmsNumber(java.lang.String)
	 */
    @Override
	public void setSmsNumber(String smsNumber) {
        this.smsNumber = smsNumber == null ? null : smsNumber.trim();
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCampaignChannel#getUrlPath()
	 */
    @Override
	public String getUrlPath() {
        return urlPath;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCampaignChannel#setUrlPath(java.lang.String)
	 */
    @Override
	public void setUrlPath(String urlPath) {
        this.urlPath = urlPath == null ? null : urlPath.trim();
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCampaignChannel#getFacebookTrackingId()
	 */
    @Override
	public String getFacebookTrackingId() {
        return facebookTrackingId;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCampaignChannel#setFacebookTrackingId(java.lang.String)
	 */
    @Override
	public void setFacebookTrackingId(String facebookTrackingId) {
        this.facebookTrackingId = facebookTrackingId == null ? null : facebookTrackingId.trim();
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCampaignChannel#getGoogleTrackingId()
	 */
    @Override
	public String getGoogleTrackingId() {
        return googleTrackingId;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCampaignChannel#setGoogleTrackingId(java.lang.String)
	 */
    @Override
	public void setGoogleTrackingId(String googleTrackingId) {
        this.googleTrackingId = googleTrackingId == null ? null : googleTrackingId.trim();
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCampaignChannel#isEnabled()
	 */
    @Override
	public boolean isEnabled() {
        return enabled;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCampaignChannel#setEnabled(boolean)
	 */
    @Override
	public void setEnabled(boolean enabled) {
        this.enabled = enabled;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCampaignChannel#getTitle()
	 */
    @Override
	public String getTitle() {
        return title;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCampaignChannel#setTitle(java.lang.String)
	 */
    @Override
	public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCampaignChannel#getImageUrl()
	 */
    @Override
	public String getImageUrl() {
        return imageUrl;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCampaignChannel#setImageUrl(java.lang.String)
	 */
    @Override
	public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl == null ? null : imageUrl.trim();
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCampaignChannel#getMainContent()
	 */
    @Override
	public String getMainContent() {
        return mainContent;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCampaignChannel#setMainContent(java.lang.String)
	 */
    @Override
	public void setMainContent(String mainContent) {
        this.mainContent = mainContent == null ? null : mainContent.trim();
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCampaignChannel#getConversionContent()
	 */
    @Override
	public String getConversionContent() {
        return conversionContent;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCampaignChannel#setConversionContent(java.lang.String)
	 */
    @Override
	public void setConversionContent(String conversionContent) {
        this.conversionContent = conversionContent == null ? null : conversionContent.trim();
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCampaignChannel#getCreatedDate()
	 */
    @Override
	public Date getCreatedDate() {
        return createdDate;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCampaignChannel#setCreatedDate(java.util.Date)
	 */
    @Override
	public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCampaignChannel#getStartDate()
	 */
    @Override
	public Date getStartDate() {
        return startDate;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCampaignChannel#setStartDate(java.util.Date)
	 */
    @Override
	public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCampaignChannel#getEndDate()
	 */
    @Override
	public Date getEndDate() {
        return endDate;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCampaignChannel#setEndDate(java.util.Date)
	 */
    @Override
	public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCampaignChannel#getLastUpdated()
	 */
    @Override
	public Date getLastUpdated() {
        return lastUpdated;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCampaignChannel#setLastUpdated(java.util.Date)
	 */
    @Override
	public void setLastUpdated(Date lastUpdated) {
        this.lastUpdated = lastUpdated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table campaign_channel
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", uid=").append(uid);
        sb.append(", campaignId=").append(campaignId);
        sb.append(", typeId=").append(typeId);
        sb.append(", name=").append(name);
        sb.append(", keyword=").append(keyword);
        sb.append(", smsNumber=").append(smsNumber);
        sb.append(", urlPath=").append(urlPath);
        sb.append(", facebookTrackingId=").append(facebookTrackingId);
        sb.append(", googleTrackingId=").append(googleTrackingId);
        sb.append(", enabled=").append(enabled);
        sb.append(", title=").append(title);
        sb.append(", imageUrl=").append(imageUrl);
        sb.append(", mainContent=").append(mainContent);
        sb.append(", conversionContent=").append(conversionContent);
        sb.append(", createdDate=").append(createdDate);
        sb.append(", startDate=").append(startDate);
        sb.append(", endDate=").append(endDate);
        sb.append(", lastUpdated=").append(lastUpdated);
        sb.append("]");
        return sb.toString();
    }
}
