package com.linuxtek.kona.app.sales.entity;

import java.math.BigDecimal;
import java.util.Date;

public class KBaseInvoice implements KInvoice {
 
	private static final long serialVersionUID = 1L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invoice.id
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invoice.app_id
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private Long appId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invoice.user_id
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invoice.account_id
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private Long accountId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invoice.currency_id
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private Long currencyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invoice.invoice_no
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private String invoiceNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invoice.start_balance
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private BigDecimal startBalance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invoice.end_balance
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private BigDecimal endBalance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invoice.subtotal
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private BigDecimal subtotal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invoice.tax
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private BigDecimal tax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invoice.shipping
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private BigDecimal shipping;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invoice.discount
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private BigDecimal discount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invoice.total
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private BigDecimal total;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invoice.amount_due
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private BigDecimal amountDue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invoice.amount_paid
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private BigDecimal amountPaid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invoice.paid
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private boolean paid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invoice.closed
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private boolean closed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invoice.created_date
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private Date createdDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invoice.invoice_date
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private Date invoiceDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invoice.due_date
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private Date dueDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invoice.paid_date
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private Date paidDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invoice.closed_date
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private Date closedDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invoice.payment_attempted
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private boolean paymentAttempted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invoice.payment_attempt_count
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private Integer paymentAttemptCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invoice.last_payment_attempt_date
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private Date lastPaymentAttemptDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invoice.next_payment_attempt_date
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private Date nextPaymentAttemptDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invoice.payment_card_last4
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private String paymentCardLast4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invoice.payment_ref
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private String paymentRef;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invoice.notes
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private String notes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invoice.last_updated
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private Date updatedDate;

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KInvoice#getId()
	 */
    @Override
	public Long getId() {
        return id;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KInvoice#setId(java.lang.Long)
	 */
    @Override
	public void setId(Long id) {
        this.id = id;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KInvoice#getAppId()
	 */
    @Override
	public Long getAppId() {
        return appId;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KInvoice#setAppId(java.lang.Long)
	 */
    @Override
	public void setAppId(Long appId) {
        this.appId = appId;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KInvoice#getUserId()
	 */
    @Override
	public Long getUserId() {
        return userId;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KInvoice#setUserId(java.lang.Long)
	 */
    @Override
	public void setUserId(Long userId) {
        this.userId = userId;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KInvoice#getAccountId()
	 */
    @Override
	public Long getAccountId() {
        return accountId;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KInvoice#setAccountId(java.lang.Long)
	 */
    @Override
	public void setAccountId(Long accountId) {
        this.accountId = accountId;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KInvoice#getCurrencyId()
	 */
    @Override
	public Long getCurrencyId() {
        return currencyId;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KInvoice#setCurrencyId(java.lang.Long)
	 */
    @Override
	public void setCurrencyId(Long currencyId) {
        this.currencyId = currencyId;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KInvoice#getInvoiceNo()
	 */
    @Override
	public String getInvoiceNo() {
        return invoiceNo;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KInvoice#setInvoiceNo(java.lang.String)
	 */
    @Override
	public void setInvoiceNo(String invoiceNo) {
        this.invoiceNo = invoiceNo == null ? null : invoiceNo.trim();
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KInvoice#getStartBalance()
	 */
    @Override
	public BigDecimal getStartBalance() {
        return startBalance;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KInvoice#setStartBalance(java.math.BigDecimal)
	 */
    @Override
	public void setStartBalance(BigDecimal startBalance) {
        this.startBalance = startBalance;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KInvoice#getEndBalance()
	 */
    @Override
	public BigDecimal getEndBalance() {
        return endBalance;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KInvoice#setEndBalance(java.math.BigDecimal)
	 */
    @Override
	public void setEndBalance(BigDecimal endBalance) {
        this.endBalance = endBalance;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KInvoice#getSubtotal()
	 */
    @Override
	public BigDecimal getSubtotal() {
        return subtotal;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KInvoice#setSubtotal(java.math.BigDecimal)
	 */
    @Override
	public void setSubtotal(BigDecimal subtotal) {
        this.subtotal = subtotal;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KInvoice#getTax()
	 */
    @Override
	public BigDecimal getTax() {
        return tax;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KInvoice#setTax(java.math.BigDecimal)
	 */
    @Override
	public void setTax(BigDecimal tax) {
        this.tax = tax;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KInvoice#getShipping()
	 */
    @Override
	public BigDecimal getShipping() {
        return shipping;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KInvoice#setShipping(java.math.BigDecimal)
	 */
    @Override
	public void setShipping(BigDecimal shipping) {
        this.shipping = shipping;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KInvoice#getDiscount()
	 */
    @Override
	public BigDecimal getDiscount() {
        return discount;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KInvoice#setDiscount(java.math.BigDecimal)
	 */
    @Override
	public void setDiscount(BigDecimal discount) {
        this.discount = discount;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KInvoice#getTotal()
	 */
    @Override
	public BigDecimal getTotal() {
        return total;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KInvoice#setTotal(java.math.BigDecimal)
	 */
    @Override
	public void setTotal(BigDecimal total) {
        this.total = total;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KInvoice#getAmountDue()
	 */
    @Override
	public BigDecimal getAmountDue() {
        return amountDue;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KInvoice#setAmountDue(java.math.BigDecimal)
	 */
    @Override
	public void setAmountDue(BigDecimal amountDue) {
        this.amountDue = amountDue;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KInvoice#getAmountPaid()
	 */
    @Override
	public BigDecimal getAmountPaid() {
        return amountPaid;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KInvoice#setAmountPaid(java.math.BigDecimal)
	 */
    @Override
	public void setAmountPaid(BigDecimal amountPaid) {
        this.amountPaid = amountPaid;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KInvoice#isPaid()
	 */
    @Override
	public boolean isPaid() {
        return paid;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KInvoice#setPaid(boolean)
	 */
    @Override
	public void setPaid(boolean paid) {
        this.paid = paid;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KInvoice#isClosed()
	 */
    @Override
	public boolean isClosed() {
        return closed;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KInvoice#setClosed(boolean)
	 */
    @Override
	public void setClosed(boolean closed) {
        this.closed = closed;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KInvoice#getCreatedDate()
	 */
    @Override
	public Date getCreatedDate() {
        return createdDate;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KInvoice#setCreatedDate(java.util.Date)
	 */
    @Override
	public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KInvoice#getInvoiceDate()
	 */
    @Override
	public Date getInvoiceDate() {
        return invoiceDate;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KInvoice#setInvoiceDate(java.util.Date)
	 */
    @Override
	public void setInvoiceDate(Date invoiceDate) {
        this.invoiceDate = invoiceDate;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KInvoice#getDueDate()
	 */
    @Override
	public Date getDueDate() {
        return dueDate;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KInvoice#setDueDate(java.util.Date)
	 */
    @Override
	public void setDueDate(Date dueDate) {
        this.dueDate = dueDate;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KInvoice#getPaidDate()
	 */
    @Override
	public Date getPaidDate() {
        return paidDate;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KInvoice#setPaidDate(java.util.Date)
	 */
    @Override
	public void setPaidDate(Date paidDate) {
        this.paidDate = paidDate;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KInvoice#getClosedDate()
	 */
    @Override
	public Date getClosedDate() {
        return closedDate;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KInvoice#setClosedDate(java.util.Date)
	 */
    @Override
	public void setClosedDate(Date closedDate) {
        this.closedDate = closedDate;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KInvoice#isPaymentAttempted()
	 */
    @Override
	public boolean isPaymentAttempted() {
        return paymentAttempted;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KInvoice#setPaymentAttempted(boolean)
	 */
    @Override
	public void setPaymentAttempted(boolean paymentAttempted) {
        this.paymentAttempted = paymentAttempted;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KInvoice#getPaymentAttemptCount()
	 */
    @Override
	public Integer getPaymentAttemptCount() {
        return paymentAttemptCount;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KInvoice#setPaymentAttemptCount(java.lang.Integer)
	 */
    @Override
	public void setPaymentAttemptCount(Integer paymentAttemptCount) {
        this.paymentAttemptCount = paymentAttemptCount;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KInvoice#getLastPaymentAttemptDate()
	 */
    @Override
	public Date getLastPaymentAttemptDate() {
        return lastPaymentAttemptDate;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KInvoice#setLastPaymentAttemptDate(java.util.Date)
	 */
    @Override
	public void setLastPaymentAttemptDate(Date lastPaymentAttemptDate) {
        this.lastPaymentAttemptDate = lastPaymentAttemptDate;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KInvoice#getNextPaymentAttemptDate()
	 */
    @Override
	public Date getNextPaymentAttemptDate() {
        return nextPaymentAttemptDate;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KInvoice#setNextPaymentAttemptDate(java.util.Date)
	 */
    @Override
	public void setNextPaymentAttemptDate(Date nextPaymentAttemptDate) {
        this.nextPaymentAttemptDate = nextPaymentAttemptDate;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KInvoice#getPaymentCardLast4()
	 */
    @Override
	public String getPaymentCardLast4() {
        return paymentCardLast4;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KInvoice#setPaymentCardLast4(java.lang.String)
	 */
    @Override
	public void setPaymentCardLast4(String paymentCardLast4) {
        this.paymentCardLast4 = paymentCardLast4 == null ? null : paymentCardLast4.trim();
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KInvoice#getPaymentRef()
	 */
    @Override
	public String getPaymentRef() {
        return paymentRef;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KInvoice#setPaymentRef(java.lang.String)
	 */
    @Override
	public void setPaymentRef(String paymentRef) {
        this.paymentRef = paymentRef == null ? null : paymentRef.trim();
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KInvoice#getNotes()
	 */
    @Override
	public String getNotes() {
        return notes;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KInvoice#setNotes(java.lang.String)
	 */
    @Override
	public void setNotes(String notes) {
        this.notes = notes == null ? null : notes.trim();
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KInvoice#getUpdatedDate()
	 */
    @Override
	public Date getUpdatedDate() {
        return updatedDate;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KInvoice#setUpdatedDate(java.util.Date)
	 */
    @Override
	public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invoice
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", appId=").append(appId);
        sb.append(", userId=").append(userId);
        sb.append(", accountId=").append(accountId);
        sb.append(", currencyId=").append(currencyId);
        sb.append(", invoiceNo=").append(invoiceNo);
        sb.append(", startBalance=").append(startBalance);
        sb.append(", endBalance=").append(endBalance);
        sb.append(", subtotal=").append(subtotal);
        sb.append(", tax=").append(tax);
        sb.append(", shipping=").append(shipping);
        sb.append(", discount=").append(discount);
        sb.append(", total=").append(total);
        sb.append(", amountDue=").append(amountDue);
        sb.append(", amountPaid=").append(amountPaid);
        sb.append(", paid=").append(paid);
        sb.append(", closed=").append(closed);
        sb.append(", createdDate=").append(createdDate);
        sb.append(", invoiceDate=").append(invoiceDate);
        sb.append(", dueDate=").append(dueDate);
        sb.append(", paidDate=").append(paidDate);
        sb.append(", closedDate=").append(closedDate);
        sb.append(", paymentAttempted=").append(paymentAttempted);
        sb.append(", paymentAttemptCount=").append(paymentAttemptCount);
        sb.append(", lastPaymentAttemptDate=").append(lastPaymentAttemptDate);
        sb.append(", nextPaymentAttemptDate=").append(nextPaymentAttemptDate);
        sb.append(", paymentCardLast4=").append(paymentCardLast4);
        sb.append(", paymentRef=").append(paymentRef);
        sb.append(", notes=").append(notes);
        sb.append(", updatedDate=").append(updatedDate);
        sb.append("]");
        return sb.toString();
    }
}
