package com.linuxtek.kona.app.sales.entity;

import java.util.Date;

public class KBaseCampaign implements KCampaign {
 
	private static final long serialVersionUID = 1L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column campaign.id
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column campaign.uid
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private String uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column campaign.app_id
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private Long appId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column campaign.promo_id
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private Long promoId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column campaign.partner_id
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private Long partnerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column campaign.name
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column campaign.display_name
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private String displayName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column campaign.description
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column campaign.enabled
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private boolean enabled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column campaign.created_date
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private Date createdDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column campaign.start_date
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private Date startDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column campaign.end_date
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private Date endDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column campaign.last_updated
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private Date updatedDate;

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCampaign#getId()
	 */
    @Override
	public Long getId() {
        return id;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCampaign#setId(java.lang.Long)
	 */
    @Override
	public void setId(Long id) {
        this.id = id;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCampaign#getUid()
	 */
    @Override
	public String getUid() {
        return uid;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCampaign#setUid(java.lang.String)
	 */
    @Override
	public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCampaign#getAppId()
	 */
    @Override
	public Long getAppId() {
        return appId;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCampaign#setAppId(java.lang.Long)
	 */
    @Override
	public void setAppId(Long appId) {
        this.appId = appId;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCampaign#getPromoId()
	 */
    @Override
	public Long getPromoId() {
        return promoId;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCampaign#setPromoId(java.lang.Long)
	 */
    @Override
	public void setPromoId(Long promoId) {
        this.promoId = promoId;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCampaign#getPartnerId()
	 */
    @Override
	public Long getPartnerId() {
        return partnerId;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCampaign#setPartnerId(java.lang.Long)
	 */
    @Override
	public void setPartnerId(Long partnerId) {
        this.partnerId = partnerId;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCampaign#getName()
	 */
    @Override
	public String getName() {
        return name;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCampaign#setName(java.lang.String)
	 */
    @Override
	public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCampaign#getDisplayName()
	 */
    @Override
	public String getDisplayName() {
        return displayName;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCampaign#setDisplayName(java.lang.String)
	 */
    @Override
	public void setDisplayName(String displayName) {
        this.displayName = displayName == null ? null : displayName.trim();
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCampaign#getDescription()
	 */
    @Override
	public String getDescription() {
        return description;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCampaign#setDescription(java.lang.String)
	 */
    @Override
	public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCampaign#isEnabled()
	 */
    @Override
	public boolean isEnabled() {
        return enabled;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCampaign#setEnabled(boolean)
	 */
    @Override
	public void setEnabled(boolean enabled) {
        this.enabled = enabled;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCampaign#getCreatedDate()
	 */
    @Override
	public Date getCreatedDate() {
        return createdDate;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCampaign#setCreatedDate(java.util.Date)
	 */
    @Override
	public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCampaign#getStartDate()
	 */
    @Override
	public Date getStartDate() {
        return startDate;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCampaign#setStartDate(java.util.Date)
	 */
    @Override
	public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCampaign#getEndDate()
	 */
    @Override
	public Date getEndDate() {
        return endDate;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCampaign#setEndDate(java.util.Date)
	 */
    @Override
	public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCampaign#getUpdatedDate()
	 */
    @Override
	public Date getUpdatedDate() {
        return updatedDate;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCampaign#setUpdatedDate(java.util.Date)
	 */
    @Override
	public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table campaign
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", uid=").append(uid);
        sb.append(", appId=").append(appId);
        sb.append(", promoId=").append(promoId);
        sb.append(", partnerId=").append(partnerId);
        sb.append(", name=").append(name);
        sb.append(", displayName=").append(displayName);
        sb.append(", description=").append(description);
        sb.append(", enabled=").append(enabled);
        sb.append(", createdDate=").append(createdDate);
        sb.append(", startDate=").append(startDate);
        sb.append(", endDate=").append(endDate);
        sb.append(", updatedDate=").append(updatedDate);
        sb.append("]");
        return sb.toString();
    }
}
