package com.linuxtek.kona.app.sales.entity;

import java.math.BigDecimal;
import java.util.Date;

public class KBaseInvoiceItem implements KInvoiceItem {

	private static final long serialVersionUID = 1L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invoice_item.id
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private Long id;
    
    private String uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invoice_item.invoice_id
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private Long invoiceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invoice_item.product_id
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private Long productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invoice_item.promo_id
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private Long promoId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invoice_item.description
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invoice_item.discount_description
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private String discountDescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invoice_item.unit_price
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private BigDecimal unitPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invoice_item.setup_fee
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private BigDecimal setupFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invoice_item.quantity
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private Integer quantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invoice_item.subtotal
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private BigDecimal subtotal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invoice_item.discount
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private BigDecimal discount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invoice_item.total
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private BigDecimal total;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invoice_item.subscription_start_date
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private Date subscriptionStartDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invoice_item.subscription_end_date
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private Date subscriptionEndDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invoice_item.created_date
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private Date createdDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invoice_item.last_updated
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private Date updatedDate;

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KInvoiceItem#getId()
	 */
    @Override
	public Long getId() {
        return id;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KInvoiceItem#setId(java.lang.Long)
	 */
    @Override
	public void setId(Long id) {
        this.id = id;
    }

    @Override
	public String getUid() {
        return uid;
    }

    @Override
	public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KInvoiceItem#getInvoiceId()
	 */
    @Override
	public Long getInvoiceId() {
        return invoiceId;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KInvoiceItem#setInvoiceId(java.lang.Long)
	 */
    @Override
	public void setInvoiceId(Long invoiceId) {
        this.invoiceId = invoiceId;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KInvoiceItem#getProductId()
	 */
    @Override
	public Long getProductId() {
        return productId;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KInvoiceItem#setProductId(java.lang.Long)
	 */
    @Override
	public void setProductId(Long productId) {
        this.productId = productId;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KInvoiceItem#getPromoId()
	 */
    @Override
	public Long getPromoId() {
        return promoId;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KInvoiceItem#setPromoId(java.lang.Long)
	 */
    @Override
	public void setPromoId(Long promoId) {
        this.promoId = promoId;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KInvoiceItem#getDescription()
	 */
    @Override
	public String getDescription() {
        return description;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KInvoiceItem#setDescription(java.lang.String)
	 */
    @Override
	public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KInvoiceItem#getDiscountDescription()
	 */
    @Override
	public String getDiscountDescription() {
        return discountDescription;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KInvoiceItem#setDiscountDescription(java.lang.String)
	 */
    @Override
	public void setDiscountDescription(String discountDescription) {
        this.discountDescription = discountDescription == null ? null : discountDescription.trim();
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KInvoiceItem#getUnitPrice()
	 */
    @Override
	public BigDecimal getUnitPrice() {
        return unitPrice;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KInvoiceItem#setUnitPrice(java.math.BigDecimal)
	 */
    @Override
	public void setUnitPrice(BigDecimal unitPrice) {
        this.unitPrice = unitPrice;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KInvoiceItem#getSetupFee()
	 */
    @Override
	public BigDecimal getSetupFee() {
        return setupFee;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KInvoiceItem#setSetupFee(java.math.BigDecimal)
	 */
    @Override
	public void setSetupFee(BigDecimal setupFee) {
        this.setupFee = setupFee;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KInvoiceItem#getQuantity()
	 */
    @Override
	public Integer getQuantity() {
        return quantity;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KInvoiceItem#setQuantity(java.lang.Integer)
	 */
    @Override
	public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KInvoiceItem#getSubtotal()
	 */
    @Override
	public BigDecimal getSubtotal() {
        return subtotal;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KInvoiceItem#setSubtotal(java.math.BigDecimal)
	 */
    @Override
	public void setSubtotal(BigDecimal subtotal) {
        this.subtotal = subtotal;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KInvoiceItem#getDiscount()
	 */
    @Override
	public BigDecimal getDiscount() {
        return discount;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KInvoiceItem#setDiscount(java.math.BigDecimal)
	 */
    @Override
	public void setDiscount(BigDecimal discount) {
        this.discount = discount;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KInvoiceItem#getTotal()
	 */
    @Override
	public BigDecimal getTotal() {
        return total;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KInvoiceItem#setTotal(java.math.BigDecimal)
	 */
    @Override
	public void setTotal(BigDecimal total) {
        this.total = total;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KInvoiceItem#getSubscriptionStartDate()
	 */
    @Override
	public Date getSubscriptionStartDate() {
        return subscriptionStartDate;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KInvoiceItem#setSubscriptionStartDate(java.util.Date)
	 */
    @Override
	public void setSubscriptionStartDate(Date subscriptionStartDate) {
        this.subscriptionStartDate = subscriptionStartDate;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KInvoiceItem#getSubscriptionEndDate()
	 */
    @Override
	public Date getSubscriptionEndDate() {
        return subscriptionEndDate;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KInvoiceItem#setSubscriptionEndDate(java.util.Date)
	 */
    @Override
	public void setSubscriptionEndDate(Date subscriptionEndDate) {
        this.subscriptionEndDate = subscriptionEndDate;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KInvoiceItem#getCreatedDate()
	 */
    @Override
	public Date getCreatedDate() {
        return createdDate;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KInvoiceItem#setCreatedDate(java.util.Date)
	 */
    @Override
	public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KInvoiceItem#getUpdatedDate()
	 */
    @Override
	public Date getUpdatedDate() {
        return updatedDate;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KInvoiceItem#setUpdatedDate(java.util.Date)
	 */
    @Override
	public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invoice_item
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", invoiceId=").append(invoiceId);
        sb.append(", productId=").append(productId);
        sb.append(", promoId=").append(promoId);
        sb.append(", description=").append(description);
        sb.append(", discountDescription=").append(discountDescription);
        sb.append(", unitPrice=").append(unitPrice);
        sb.append(", setupFee=").append(setupFee);
        sb.append(", quantity=").append(quantity);
        sb.append(", subtotal=").append(subtotal);
        sb.append(", discount=").append(discount);
        sb.append(", total=").append(total);
        sb.append(", subscriptionStartDate=").append(subscriptionStartDate);
        sb.append(", subscriptionEndDate=").append(subscriptionEndDate);
        sb.append(", createdDate=").append(createdDate);
        sb.append(", updatedDate=").append(updatedDate);
        sb.append("]");
        return sb.toString();
    }
}
