package com.linuxtek.kona.app.sales.entity;

import java.util.Date;

public class KBaseProductPurchase implements KProductPurchase {

	private static final long serialVersionUID = 1L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_purchase.id
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_purchase.parent_id
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private Long parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_purchase.account_id
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private Long accountId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_purchase.user_id
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_purchase.product_id
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private Long productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_purchase.app_id
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private Long appId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_purchase.promo_id
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private Long promoId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_purchase.partner_id
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private Long partnerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_purchase.campaign_id
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private Long campaignId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_purchase.payment_type_id
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private Long paymentTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_purchase.kind
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private String kind;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_purchase.invoice_no
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private String invoiceNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_purchase.auto_renew
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private boolean autoRenew;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_purchase.enabled
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private boolean enabled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_purchase.created_date
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private Date createdDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_purchase.expiration_date
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private Date expirationDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_purchase.last_updated
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private Date lastUpdated;

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KProductPurchase#getId()
	 */
    @Override
	public Long getId() {
        return id;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KProductPurchase#setId(java.lang.Long)
	 */
    @Override
	public void setId(Long id) {
        this.id = id;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KProductPurchase#getParentId()
	 */
    @Override
	public Long getParentId() {
        return parentId;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KProductPurchase#setParentId(java.lang.Long)
	 */
    @Override
	public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KProductPurchase#getAccountId()
	 */
    @Override
	public Long getAccountId() {
        return accountId;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KProductPurchase#setAccountId(java.lang.Long)
	 */
    @Override
	public void setAccountId(Long accountId) {
        this.accountId = accountId;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KProductPurchase#getUserId()
	 */
    @Override
	public Long getUserId() {
        return userId;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KProductPurchase#setUserId(java.lang.Long)
	 */
    @Override
	public void setUserId(Long userId) {
        this.userId = userId;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KProductPurchase#getProductId()
	 */
    @Override
	public Long getProductId() {
        return productId;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KProductPurchase#setProductId(java.lang.Long)
	 */
    @Override
	public void setProductId(Long productId) {
        this.productId = productId;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KProductPurchase#getAppId()
	 */
    @Override
	public Long getAppId() {
        return appId;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KProductPurchase#setAppId(java.lang.Long)
	 */
    @Override
	public void setAppId(Long appId) {
        this.appId = appId;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KProductPurchase#getPromoId()
	 */
    @Override
	public Long getPromoId() {
        return promoId;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KProductPurchase#setPromoId(java.lang.Long)
	 */
    @Override
	public void setPromoId(Long promoId) {
        this.promoId = promoId;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KProductPurchase#getPartnerId()
	 */
    @Override
	public Long getPartnerId() {
        return partnerId;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KProductPurchase#setPartnerId(java.lang.Long)
	 */
    @Override
	public void setPartnerId(Long partnerId) {
        this.partnerId = partnerId;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KProductPurchase#getCampaignId()
	 */
    @Override
	public Long getCampaignId() {
        return campaignId;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KProductPurchase#setCampaignId(java.lang.Long)
	 */
    @Override
	public void setCampaignId(Long campaignId) {
        this.campaignId = campaignId;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KProductPurchase#getPaymentTypeId()
	 */
    @Override
	public Long getPaymentTypeId() {
        return paymentTypeId;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KProductPurchase#setPaymentTypeId(java.lang.Long)
	 */
    @Override
	public void setPaymentTypeId(Long paymentTypeId) {
        this.paymentTypeId = paymentTypeId;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KProductPurchase#getKind()
	 */
    @Override
	public String getKind() {
        return kind;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KProductPurchase#setKind(java.lang.String)
	 */
    @Override
	public void setKind(String kind) {
        this.kind = kind == null ? null : kind.trim();
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KProductPurchase#getInvoiceNo()
	 */
    @Override
	public String getInvoiceNo() {
        return invoiceNo;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KProductPurchase#setInvoiceNo(java.lang.String)
	 */
    @Override
	public void setInvoiceNo(String invoiceNo) {
        this.invoiceNo = invoiceNo == null ? null : invoiceNo.trim();
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KProductPurchase#isAutoRenew()
	 */
    @Override
	public boolean isAutoRenew() {
        return autoRenew;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KProductPurchase#setAutoRenew(boolean)
	 */
    @Override
	public void setAutoRenew(boolean autoRenew) {
        this.autoRenew = autoRenew;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KProductPurchase#isEnabled()
	 */
    @Override
	public boolean isEnabled() {
        return enabled;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KProductPurchase#setEnabled(boolean)
	 */
    @Override
	public void setEnabled(boolean enabled) {
        this.enabled = enabled;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KProductPurchase#getCreatedDate()
	 */
    @Override
	public Date getCreatedDate() {
        return createdDate;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KProductPurchase#setCreatedDate(java.util.Date)
	 */
    @Override
	public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KProductPurchase#getExpirationDate()
	 */
    @Override
	public Date getExpirationDate() {
        return expirationDate;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KProductPurchase#setExpirationDate(java.util.Date)
	 */
    @Override
	public void setExpirationDate(Date expirationDate) {
        this.expirationDate = expirationDate;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KProductPurchase#getLastUpdated()
	 */
    @Override
	public Date getLastUpdated() {
        return lastUpdated;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KProductPurchase#setLastUpdated(java.util.Date)
	 */
    @Override
	public void setLastUpdated(Date lastUpdated) {
        this.lastUpdated = lastUpdated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_purchase
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", parentId=").append(parentId);
        sb.append(", accountId=").append(accountId);
        sb.append(", userId=").append(userId);
        sb.append(", productId=").append(productId);
        sb.append(", appId=").append(appId);
        sb.append(", promoId=").append(promoId);
        sb.append(", partnerId=").append(partnerId);
        sb.append(", campaignId=").append(campaignId);
        sb.append(", paymentTypeId=").append(paymentTypeId);
        sb.append(", kind=").append(kind);
        sb.append(", invoiceNo=").append(invoiceNo);
        sb.append(", autoRenew=").append(autoRenew);
        sb.append(", enabled=").append(enabled);
        sb.append(", createdDate=").append(createdDate);
        sb.append(", expirationDate=").append(expirationDate);
        sb.append(", lastUpdated=").append(lastUpdated);
        sb.append("]");
        return sb.toString();
    }
}
