package com.linuxtek.kona.app.sales.entity;

import java.math.BigDecimal;
import java.util.Date;

public class KBaseProduct implements KProduct {
 
	private static final long serialVersionUID = 1L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.id
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.app_id
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private Long appId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.name
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.display_name
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private String displayName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.display_order
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private Integer displayOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.description
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.price
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private BigDecimal price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.setup_fee
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private BigDecimal setupFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.trial_days
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private Integer trialDays;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.subscription
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private boolean subscription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.subscription_days
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private Integer subscriptionDays;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.support_type
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private String supportType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.active
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private boolean active;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.created_date
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private Date createdDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.last_updated
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private Date lastUpdated;

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KProduct#getId()
	 */
    @Override
	public Long getId() {
        return id;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KProduct#setId(java.lang.Long)
	 */
    @Override
	public void setId(Long id) {
        this.id = id;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KProduct#getAppId()
	 */
    @Override
	public Long getAppId() {
        return appId;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KProduct#setAppId(java.lang.Long)
	 */
    @Override
	public void setAppId(Long appId) {
        this.appId = appId;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KProduct#getName()
	 */
    @Override
	public String getName() {
        return name;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KProduct#setName(java.lang.String)
	 */
    @Override
	public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KProduct#getDisplayName()
	 */
    @Override
	public String getDisplayName() {
        return displayName;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KProduct#setDisplayName(java.lang.String)
	 */
    @Override
	public void setDisplayName(String displayName) {
        this.displayName = displayName == null ? null : displayName.trim();
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KProduct#getDisplayOrder()
	 */
    @Override
	public Integer getDisplayOrder() {
        return displayOrder;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KProduct#setDisplayOrder(java.lang.Integer)
	 */
    @Override
	public void setDisplayOrder(Integer displayOrder) {
        this.displayOrder = displayOrder;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KProduct#getDescription()
	 */
    @Override
	public String getDescription() {
        return description;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KProduct#setDescription(java.lang.String)
	 */
    @Override
	public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KProduct#getPrice()
	 */
    @Override
	public BigDecimal getPrice() {
        return price;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KProduct#setPrice(java.math.BigDecimal)
	 */
    @Override
	public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KProduct#getSetupFee()
	 */
    @Override
	public BigDecimal getSetupFee() {
        return setupFee;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KProduct#setSetupFee(java.math.BigDecimal)
	 */
    @Override
	public void setSetupFee(BigDecimal setupFee) {
        this.setupFee = setupFee;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KProduct#getTrialDays()
	 */
    @Override
	public Integer getTrialDays() {
        return trialDays;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KProduct#setTrialDays(java.lang.Integer)
	 */
    @Override
	public void setTrialDays(Integer trialDays) {
        this.trialDays = trialDays;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KProduct#isSubscription()
	 */
    @Override
	public boolean isSubscription() {
        return subscription;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KProduct#setSubscription(boolean)
	 */
    @Override
	public void setSubscription(boolean subscription) {
        this.subscription = subscription;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KProduct#getSubscriptionDays()
	 */
    @Override
	public Integer getSubscriptionDays() {
        return subscriptionDays;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KProduct#setSubscriptionDays(java.lang.Integer)
	 */
    @Override
	public void setSubscriptionDays(Integer subscriptionDays) {
        this.subscriptionDays = subscriptionDays;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KProduct#getSupportType()
	 */
    @Override
	public String getSupportType() {
        return supportType;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KProduct#setSupportType(java.lang.String)
	 */
    @Override
	public void setSupportType(String supportType) {
        this.supportType = supportType == null ? null : supportType.trim();
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KProduct#isActive()
	 */
    @Override
	public boolean isActive() {
        return active;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KProduct#setActive(boolean)
	 */
    @Override
	public void setActive(boolean active) {
        this.active = active;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KProduct#getCreatedDate()
	 */
    @Override
	public Date getCreatedDate() {
        return createdDate;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KProduct#setCreatedDate(java.util.Date)
	 */
    @Override
	public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KProduct#getLastUpdated()
	 */
    @Override
	public Date getLastUpdated() {
        return lastUpdated;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KProduct#setLastUpdated(java.util.Date)
	 */
    @Override
	public void setLastUpdated(Date lastUpdated) {
        this.lastUpdated = lastUpdated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", appId=").append(appId);
        sb.append(", name=").append(name);
        sb.append(", displayName=").append(displayName);
        sb.append(", displayOrder=").append(displayOrder);
        sb.append(", description=").append(description);
        sb.append(", price=").append(price);
        sb.append(", setupFee=").append(setupFee);
        sb.append(", trialDays=").append(trialDays);
        sb.append(", subscription=").append(subscription);
        sb.append(", subscriptionDays=").append(subscriptionDays);
        sb.append(", supportType=").append(supportType);
        sb.append(", active=").append(active);
        sb.append(", createdDate=").append(createdDate);
        sb.append(", lastUpdated=").append(lastUpdated);
        sb.append("]");
        return sb.toString();
    }
}
