package com.linuxtek.kona.app.sales.entity;

import java.util.Date;

public class KBaseCampaignEvent implements KCampaignEvent {
 
	private static final long serialVersionUID = 1L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column campaign_event.id
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column campaign_event.uid
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private String uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column campaign_event.campaign_id
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private Long campaignId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column campaign_event.channel_id
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private Long channelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column campaign_event.user_id
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column campaign_event.event_category
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private String eventCategory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column campaign_event.event_name
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private String eventName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column campaign_event.event_label
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private String eventLabel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column campaign_event.event_value
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private String eventValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column campaign_event.mobile_number
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private String mobileNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column campaign_event.url
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column campaign_event.hostname
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private String hostname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column campaign_event.browser
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private String browser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column campaign_event.latitude
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private Double latitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column campaign_event.longitude
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private Double longitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column campaign_event.created_date
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private Date createdDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column campaign_event.last_updated
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    private Date lastUpdated;

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCampaignEvent#getId()
	 */
    @Override
	public Long getId() {
        return id;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCampaignEvent#setId(java.lang.Long)
	 */
    @Override
	public void setId(Long id) {
        this.id = id;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCampaignEvent#getUid()
	 */
    @Override
	public String getUid() {
        return uid;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCampaignEvent#setUid(java.lang.String)
	 */
    @Override
	public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCampaignEvent#getCampaignId()
	 */
    @Override
	public Long getCampaignId() {
        return campaignId;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCampaignEvent#setCampaignId(java.lang.Long)
	 */
    @Override
	public void setCampaignId(Long campaignId) {
        this.campaignId = campaignId;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCampaignEvent#getChannelId()
	 */
    @Override
	public Long getChannelId() {
        return channelId;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCampaignEvent#setChannelId(java.lang.Long)
	 */
    @Override
	public void setChannelId(Long channelId) {
        this.channelId = channelId;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCampaignEvent#getUserId()
	 */
    @Override
	public Long getUserId() {
        return userId;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCampaignEvent#setUserId(java.lang.Long)
	 */
    @Override
	public void setUserId(Long userId) {
        this.userId = userId;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCampaignEvent#getEventCategory()
	 */
    @Override
	public String getEventCategory() {
        return eventCategory;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCampaignEvent#setEventCategory(java.lang.String)
	 */
    @Override
	public void setEventCategory(String eventCategory) {
        this.eventCategory = eventCategory == null ? null : eventCategory.trim();
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCampaignEvent#getEventName()
	 */
    @Override
	public String getEventName() {
        return eventName;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCampaignEvent#setEventName(java.lang.String)
	 */
    @Override
	public void setEventName(String eventName) {
        this.eventName = eventName == null ? null : eventName.trim();
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCampaignEvent#getEventLabel()
	 */
    @Override
	public String getEventLabel() {
        return eventLabel;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCampaignEvent#setEventLabel(java.lang.String)
	 */
    @Override
	public void setEventLabel(String eventLabel) {
        this.eventLabel = eventLabel == null ? null : eventLabel.trim();
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCampaignEvent#getEventValue()
	 */
    @Override
	public String getEventValue() {
        return eventValue;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCampaignEvent#setEventValue(java.lang.String)
	 */
    @Override
	public void setEventValue(String eventValue) {
        this.eventValue = eventValue == null ? null : eventValue.trim();
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCampaignEvent#getMobileNumber()
	 */
    @Override
	public String getMobileNumber() {
        return mobileNumber;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCampaignEvent#setMobileNumber(java.lang.String)
	 */
    @Override
	public void setMobileNumber(String mobileNumber) {
        this.mobileNumber = mobileNumber == null ? null : mobileNumber.trim();
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCampaignEvent#getUrl()
	 */
    @Override
	public String getUrl() {
        return url;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCampaignEvent#setUrl(java.lang.String)
	 */
    @Override
	public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCampaignEvent#getHostname()
	 */
    @Override
	public String getHostname() {
        return hostname;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCampaignEvent#setHostname(java.lang.String)
	 */
    @Override
	public void setHostname(String hostname) {
        this.hostname = hostname == null ? null : hostname.trim();
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCampaignEvent#getBrowser()
	 */
    @Override
	public String getBrowser() {
        return browser;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCampaignEvent#setBrowser(java.lang.String)
	 */
    @Override
	public void setBrowser(String browser) {
        this.browser = browser == null ? null : browser.trim();
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCampaignEvent#getLatitude()
	 */
    @Override
	public Double getLatitude() {
        return latitude;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCampaignEvent#setLatitude(java.lang.Double)
	 */
    @Override
	public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCampaignEvent#getLongitude()
	 */
    @Override
	public Double getLongitude() {
        return longitude;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCampaignEvent#setLongitude(java.lang.Double)
	 */
    @Override
	public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCampaignEvent#getCreatedDate()
	 */
    @Override
	public Date getCreatedDate() {
        return createdDate;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCampaignEvent#setCreatedDate(java.util.Date)
	 */
    @Override
	public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCampaignEvent#getLastUpdated()
	 */
    @Override
	public Date getLastUpdated() {
        return lastUpdated;
    }

    /* (non-Javadoc)
	 * @see com.linuxtek.kona.app.sales.entity.KCampaignEvent#setLastUpdated(java.util.Date)
	 */
    @Override
	public void setLastUpdated(Date lastUpdated) {
        this.lastUpdated = lastUpdated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table campaign_event
     *
     * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", uid=").append(uid);
        sb.append(", campaignId=").append(campaignId);
        sb.append(", channelId=").append(channelId);
        sb.append(", userId=").append(userId);
        sb.append(", eventCategory=").append(eventCategory);
        sb.append(", eventName=").append(eventName);
        sb.append(", eventLabel=").append(eventLabel);
        sb.append(", eventValue=").append(eventValue);
        sb.append(", mobileNumber=").append(mobileNumber);
        sb.append(", url=").append(url);
        sb.append(", hostname=").append(hostname);
        sb.append(", browser=").append(browser);
        sb.append(", latitude=").append(latitude);
        sb.append(", longitude=").append(longitude);
        sb.append(", createdDate=").append(createdDate);
        sb.append(", lastUpdated=").append(lastUpdated);
        sb.append("]");
        return sb.toString();
    }
}
