package com.linuxtek.kona.app.sales.entity;

import java.util.Date;

import com.linuxtek.kona.data.entity.KEntityObject;

public interface KCampaignChannel extends KEntityObject {

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column campaign_channel.id
	 *
	 * @return the value of campaign_channel.id
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	Long getId();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column campaign_channel.id
	 *
	 * @param id the value for campaign_channel.id
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setId(Long id);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column campaign_channel.uid
	 *
	 * @return the value of campaign_channel.uid
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	String getUid();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column campaign_channel.uid
	 *
	 * @param uid the value for campaign_channel.uid
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setUid(String uid);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column campaign_channel.campaign_id
	 *
	 * @return the value of campaign_channel.campaign_id
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	Long getCampaignId();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column campaign_channel.campaign_id
	 *
	 * @param campaignId the value for campaign_channel.campaign_id
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setCampaignId(Long campaignId);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column campaign_channel.type_id
	 *
	 * @return the value of campaign_channel.type_id
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	Long getTypeId();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column campaign_channel.type_id
	 *
	 * @param typeId the value for campaign_channel.type_id
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setTypeId(Long typeId);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column campaign_channel.name
	 *
	 * @return the value of campaign_channel.name
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	String getName();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column campaign_channel.name
	 *
	 * @param name the value for campaign_channel.name
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setName(String name);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column campaign_channel.keyword
	 *
	 * @return the value of campaign_channel.keyword
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	String getKeyword();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column campaign_channel.keyword
	 *
	 * @param keyword the value for campaign_channel.keyword
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setKeyword(String keyword);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column campaign_channel.sms_number
	 *
	 * @return the value of campaign_channel.sms_number
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	String getSmsNumber();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column campaign_channel.sms_number
	 *
	 * @param smsNumber the value for campaign_channel.sms_number
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setSmsNumber(String smsNumber);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column campaign_channel.url_path
	 *
	 * @return the value of campaign_channel.url_path
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	String getUrlPath();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column campaign_channel.url_path
	 *
	 * @param urlPath the value for campaign_channel.url_path
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setUrlPath(String urlPath);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column campaign_channel.facebook_tracking_id
	 *
	 * @return the value of campaign_channel.facebook_tracking_id
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	String getFacebookTrackingId();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column campaign_channel.facebook_tracking_id
	 *
	 * @param facebookTrackingId the value for campaign_channel.facebook_tracking_id
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setFacebookTrackingId(String facebookTrackingId);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column campaign_channel.google_tracking_id
	 *
	 * @return the value of campaign_channel.google_tracking_id
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	String getGoogleTrackingId();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column campaign_channel.google_tracking_id
	 *
	 * @param googleTrackingId the value for campaign_channel.google_tracking_id
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setGoogleTrackingId(String googleTrackingId);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column campaign_channel.enabled
	 *
	 * @return the value of campaign_channel.enabled
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	boolean isEnabled();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column campaign_channel.enabled
	 *
	 * @param enabled the value for campaign_channel.enabled
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setEnabled(boolean enabled);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column campaign_channel.title
	 *
	 * @return the value of campaign_channel.title
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	String getTitle();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column campaign_channel.title
	 *
	 * @param title the value for campaign_channel.title
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setTitle(String title);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column campaign_channel.image_url
	 *
	 * @return the value of campaign_channel.image_url
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	String getImageUrl();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column campaign_channel.image_url
	 *
	 * @param imageUrl the value for campaign_channel.image_url
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setImageUrl(String imageUrl);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column campaign_channel.main_content
	 *
	 * @return the value of campaign_channel.main_content
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	String getMainContent();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column campaign_channel.main_content
	 *
	 * @param mainContent the value for campaign_channel.main_content
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setMainContent(String mainContent);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column campaign_channel.conversion_content
	 *
	 * @return the value of campaign_channel.conversion_content
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	String getConversionContent();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column campaign_channel.conversion_content
	 *
	 * @param conversionContent the value for campaign_channel.conversion_content
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setConversionContent(String conversionContent);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column campaign_channel.created_date
	 *
	 * @return the value of campaign_channel.created_date
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	Date getCreatedDate();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column campaign_channel.created_date
	 *
	 * @param createdDate the value for campaign_channel.created_date
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setCreatedDate(Date createdDate);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column campaign_channel.start_date
	 *
	 * @return the value of campaign_channel.start_date
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	Date getStartDate();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column campaign_channel.start_date
	 *
	 * @param startDate the value for campaign_channel.start_date
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setStartDate(Date startDate);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column campaign_channel.end_date
	 *
	 * @return the value of campaign_channel.end_date
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	Date getEndDate();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column campaign_channel.end_date
	 *
	 * @param endDate the value for campaign_channel.end_date
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setEndDate(Date endDate);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column campaign_channel.last_updated
	 *
	 * @return the value of campaign_channel.last_updated
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	Date getLastUpdated();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column campaign_channel.last_updated
	 *
	 * @param lastUpdated the value for campaign_channel.last_updated
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setLastUpdated(Date lastUpdated);

}