package com.linuxtek.kona.app.sales.entity;

import java.util.Date;

import com.linuxtek.kona.data.entity.KEntityObject;

public interface KCampaignEvent extends KEntityObject {

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column campaign_event.id
	 *
	 * @return the value of campaign_event.id
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	Long getId();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column campaign_event.id
	 *
	 * @param id the value for campaign_event.id
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setId(Long id);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column campaign_event.uid
	 *
	 * @return the value of campaign_event.uid
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	String getUid();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column campaign_event.uid
	 *
	 * @param uid the value for campaign_event.uid
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setUid(String uid);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column campaign_event.campaign_id
	 *
	 * @return the value of campaign_event.campaign_id
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	Long getCampaignId();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column campaign_event.campaign_id
	 *
	 * @param campaignId the value for campaign_event.campaign_id
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setCampaignId(Long campaignId);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column campaign_event.channel_id
	 *
	 * @return the value of campaign_event.channel_id
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	Long getChannelId();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column campaign_event.channel_id
	 *
	 * @param channelId the value for campaign_event.channel_id
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setChannelId(Long channelId);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column campaign_event.user_id
	 *
	 * @return the value of campaign_event.user_id
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	Long getUserId();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column campaign_event.user_id
	 *
	 * @param userId the value for campaign_event.user_id
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setUserId(Long userId);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column campaign_event.event_category
	 *
	 * @return the value of campaign_event.event_category
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	String getEventCategory();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column campaign_event.event_category
	 *
	 * @param eventCategory the value for campaign_event.event_category
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setEventCategory(String eventCategory);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column campaign_event.event_name
	 *
	 * @return the value of campaign_event.event_name
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	String getEventName();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column campaign_event.event_name
	 *
	 * @param eventName the value for campaign_event.event_name
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setEventName(String eventName);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column campaign_event.event_label
	 *
	 * @return the value of campaign_event.event_label
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	String getEventLabel();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column campaign_event.event_label
	 *
	 * @param eventLabel the value for campaign_event.event_label
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setEventLabel(String eventLabel);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column campaign_event.event_value
	 *
	 * @return the value of campaign_event.event_value
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	String getEventValue();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column campaign_event.event_value
	 *
	 * @param eventValue the value for campaign_event.event_value
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setEventValue(String eventValue);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column campaign_event.mobile_number
	 *
	 * @return the value of campaign_event.mobile_number
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	String getMobileNumber();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column campaign_event.mobile_number
	 *
	 * @param mobileNumber the value for campaign_event.mobile_number
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setMobileNumber(String mobileNumber);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column campaign_event.url
	 *
	 * @return the value of campaign_event.url
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	String getUrl();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column campaign_event.url
	 *
	 * @param url the value for campaign_event.url
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setUrl(String url);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column campaign_event.hostname
	 *
	 * @return the value of campaign_event.hostname
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	String getHostname();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column campaign_event.hostname
	 *
	 * @param hostname the value for campaign_event.hostname
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setHostname(String hostname);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column campaign_event.browser
	 *
	 * @return the value of campaign_event.browser
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	String getBrowser();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column campaign_event.browser
	 *
	 * @param browser the value for campaign_event.browser
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setBrowser(String browser);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column campaign_event.latitude
	 *
	 * @return the value of campaign_event.latitude
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	Double getLatitude();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column campaign_event.latitude
	 *
	 * @param latitude the value for campaign_event.latitude
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setLatitude(Double latitude);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column campaign_event.longitude
	 *
	 * @return the value of campaign_event.longitude
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	Double getLongitude();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column campaign_event.longitude
	 *
	 * @param longitude the value for campaign_event.longitude
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setLongitude(Double longitude);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column campaign_event.created_date
	 *
	 * @return the value of campaign_event.created_date
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	Date getCreatedDate();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column campaign_event.created_date
	 *
	 * @param createdDate the value for campaign_event.created_date
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setCreatedDate(Date createdDate);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column campaign_event.last_updated
	 *
	 * @return the value of campaign_event.last_updated
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	Date getLastUpdated();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column campaign_event.last_updated
	 *
	 * @param lastUpdated the value for campaign_event.last_updated
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setLastUpdated(Date lastUpdated);

}