package com.linuxtek.kona.app.sales.entity;

import java.util.Date;

import com.linuxtek.kona.data.entity.KEntityObject;

public interface KCampaign extends KEntityObject {

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column campaign.id
	 *
	 * @return the value of campaign.id
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	Long getId();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column campaign.id
	 *
	 * @param id the value for campaign.id
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setId(Long id);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column campaign.uid
	 *
	 * @return the value of campaign.uid
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	String getUid();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column campaign.uid
	 *
	 * @param uid the value for campaign.uid
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setUid(String uid);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column campaign.app_id
	 *
	 * @return the value of campaign.app_id
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	Long getAppId();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column campaign.app_id
	 *
	 * @param appId the value for campaign.app_id
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setAppId(Long appId);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column campaign.promo_id
	 *
	 * @return the value of campaign.promo_id
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	Long getPromoId();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column campaign.promo_id
	 *
	 * @param promoId the value for campaign.promo_id
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setPromoId(Long promoId);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column campaign.partner_id
	 *
	 * @return the value of campaign.partner_id
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	Long getPartnerId();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column campaign.partner_id
	 *
	 * @param partnerId the value for campaign.partner_id
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setPartnerId(Long partnerId);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column campaign.name
	 *
	 * @return the value of campaign.name
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	String getName();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column campaign.name
	 *
	 * @param name the value for campaign.name
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setName(String name);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column campaign.display_name
	 *
	 * @return the value of campaign.display_name
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	String getDisplayName();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column campaign.display_name
	 *
	 * @param displayName the value for campaign.display_name
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setDisplayName(String displayName);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column campaign.description
	 *
	 * @return the value of campaign.description
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	String getDescription();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column campaign.description
	 *
	 * @param description the value for campaign.description
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setDescription(String description);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column campaign.enabled
	 *
	 * @return the value of campaign.enabled
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	boolean isEnabled();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column campaign.enabled
	 *
	 * @param enabled the value for campaign.enabled
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setEnabled(boolean enabled);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column campaign.created_date
	 *
	 * @return the value of campaign.created_date
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	Date getCreatedDate();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column campaign.created_date
	 *
	 * @param createdDate the value for campaign.created_date
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setCreatedDate(Date createdDate);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column campaign.start_date
	 *
	 * @return the value of campaign.start_date
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	Date getStartDate();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column campaign.start_date
	 *
	 * @param startDate the value for campaign.start_date
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setStartDate(Date startDate);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column campaign.end_date
	 *
	 * @return the value of campaign.end_date
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	Date getEndDate();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column campaign.end_date
	 *
	 * @param endDate the value for campaign.end_date
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setEndDate(Date endDate);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column campaign.last_updated
	 *
	 * @return the value of campaign.last_updated
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	Date getLastUpdated();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column campaign.last_updated
	 *
	 * @param lastUpdated the value for campaign.last_updated
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setLastUpdated(Date lastUpdated);

}