package com.linuxtek.kona.app.sales.entity;

import java.math.BigDecimal;
import java.util.Date;

import com.linuxtek.kona.data.entity.KEntityObject;

public interface KCartItem extends KEntityObject {

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column cart_item.id
	 *
	 * @return the value of cart_item.id
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	Long getId();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column cart_item.id
	 *
	 * @param id the value for cart_item.id
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setId(Long id);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column cart_item.cart_id
	 *
	 * @return the value of cart_item.cart_id
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	Long getCartId();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column cart_item.cart_id
	 *
	 * @param cartId the value for cart_item.cart_id
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setCartId(Long cartId);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column cart_item.product_id
	 *
	 * @return the value of cart_item.product_id
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	Long getProductId();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column cart_item.product_id
	 *
	 * @param productId the value for cart_item.product_id
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setProductId(Long productId);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column cart_item.promo_id
	 *
	 * @return the value of cart_item.promo_id
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	Long getPromoId();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column cart_item.promo_id
	 *
	 * @param promoId the value for cart_item.promo_id
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setPromoId(Long promoId);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column cart_item.quantity
	 *
	 * @return the value of cart_item.quantity
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	Integer getQuantity();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column cart_item.quantity
	 *
	 * @param quantity the value for cart_item.quantity
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setQuantity(Integer quantity);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column cart_item.description
	 *
	 * @return the value of cart_item.description
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	String getDescription();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column cart_item.description
	 *
	 * @param description the value for cart_item.description
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setDescription(String description);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column cart_item.discount_description
	 *
	 * @return the value of cart_item.discount_description
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	String getDiscountDescription();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column cart_item.discount_description
	 *
	 * @param discountDescription the value for cart_item.discount_description
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setDiscountDescription(String discountDescription);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column cart_item.unit_price
	 *
	 * @return the value of cart_item.unit_price
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	BigDecimal getUnitPrice();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column cart_item.unit_price
	 *
	 * @param unitPrice the value for cart_item.unit_price
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setUnitPrice(BigDecimal unitPrice);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column cart_item.setup_fee
	 *
	 * @return the value of cart_item.setup_fee
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	BigDecimal getSetupFee();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column cart_item.setup_fee
	 *
	 * @param setupFee the value for cart_item.setup_fee
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setSetupFee(BigDecimal setupFee);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column cart_item.subtotal
	 *
	 * @return the value of cart_item.subtotal
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	BigDecimal getSubtotal();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column cart_item.subtotal
	 *
	 * @param subtotal the value for cart_item.subtotal
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setSubtotal(BigDecimal subtotal);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column cart_item.discount
	 *
	 * @return the value of cart_item.discount
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	BigDecimal getDiscount();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column cart_item.discount
	 *
	 * @param discount the value for cart_item.discount
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setDiscount(BigDecimal discount);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column cart_item.total
	 *
	 * @return the value of cart_item.total
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	BigDecimal getTotal();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column cart_item.total
	 *
	 * @param total the value for cart_item.total
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setTotal(BigDecimal total);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column cart_item.created_date
	 *
	 * @return the value of cart_item.created_date
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	Date getCreatedDate();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column cart_item.created_date
	 *
	 * @param createdDate the value for cart_item.created_date
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setCreatedDate(Date createdDate);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column cart_item.subscription_start_date
	 *
	 * @return the value of cart_item.subscription_start_date
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	Date getSubscriptionStartDate();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column cart_item.subscription_start_date
	 *
	 * @param subscriptionStartDate the value for cart_item.subscription_start_date
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setSubscriptionStartDate(Date subscriptionStartDate);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column cart_item.subscription_end_date
	 *
	 * @return the value of cart_item.subscription_end_date
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	Date getSubscriptionEndDate();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column cart_item.subscription_end_date
	 *
	 * @param subscriptionEndDate the value for cart_item.subscription_end_date
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setSubscriptionEndDate(Date subscriptionEndDate);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column cart_item.last_updated
	 *
	 * @return the value of cart_item.last_updated
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	Date getUpdatedDate();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column cart_item.last_updated
	 *
	 * @param updatedDate the value for cart_item.last_updated
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setUpdatedDate(Date updatedDate);

}