package com.linuxtek.kona.app.sales.entity;

import java.math.BigDecimal;
import java.util.Date;

import com.linuxtek.kona.data.entity.KEntityObject;

public interface KPayment extends KEntityObject {

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column payment.id
	 *
	 * @return the value of payment.id
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	Long getId();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column payment.id
	 *
	 * @param id the value for payment.id
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setId(Long id);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column payment.app_id
	 *
	 * @return the value of payment.app_id
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	Long getAppId();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column payment.app_id
	 *
	 * @param appId the value for payment.app_id
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setAppId(Long appId);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column payment.type_id
	 *
	 * @return the value of payment.type_id
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	Long getTypeId();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column payment.type_id
	 *
	 * @param typeId the value for payment.type_id
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setTypeId(Long typeId);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column payment.status_id
	 *
	 * @return the value of payment.status_id
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	Long getStatusId();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column payment.status_id
	 *
	 * @param statusId the value for payment.status_id
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setStatusId(Long statusId);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column payment.currency_id
	 *
	 * @return the value of payment.currency_id
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	Long getCurrencyId();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column payment.currency_id
	 *
	 * @param currencyId the value for payment.currency_id
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setCurrencyId(Long currencyId);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column payment.user_id
	 *
	 * @return the value of payment.user_id
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	Long getUserId();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column payment.user_id
	 *
	 * @param userId the value for payment.user_id
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setUserId(Long userId);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column payment.account_id
	 *
	 * @return the value of payment.account_id
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	Long getAccountId();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column payment.account_id
	 *
	 * @param accountId the value for payment.account_id
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setAccountId(Long accountId);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column payment.invoice_id
	 *
	 * @return the value of payment.invoice_id
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	Long getInvoiceId();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column payment.invoice_id
	 *
	 * @param invoiceId the value for payment.invoice_id
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setInvoiceId(Long invoiceId);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column payment.promo_id
	 *
	 * @return the value of payment.promo_id
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	Long getPromoId();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column payment.promo_id
	 *
	 * @param promoId the value for payment.promo_id
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setPromoId(Long promoId);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column payment.session_id
	 *
	 * @return the value of payment.session_id
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	String getSessionId();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column payment.session_id
	 *
	 * @param sessionId the value for payment.session_id
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setSessionId(String sessionId);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column payment.access_token
	 *
	 * @return the value of payment.access_token
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	String getAccessToken();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column payment.access_token
	 *
	 * @param accessToken the value for payment.access_token
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setAccessToken(String accessToken);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column payment.hostname
	 *
	 * @return the value of payment.hostname
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	String getHostname();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column payment.hostname
	 *
	 * @param hostname the value for payment.hostname
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setHostname(String hostname);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column payment.browser
	 *
	 * @return the value of payment.browser
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	String getBrowser();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column payment.browser
	 *
	 * @param browser the value for payment.browser
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setBrowser(String browser);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column payment.latitude
	 *
	 * @return the value of payment.latitude
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	Double getLatitude();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column payment.latitude
	 *
	 * @param latitude the value for payment.latitude
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setLatitude(Double latitude);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column payment.longitude
	 *
	 * @return the value of payment.longitude
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	Double getLongitude();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column payment.longitude
	 *
	 * @param longitude the value for payment.longitude
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setLongitude(Double longitude);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column payment.card_token
	 *
	 * @return the value of payment.card_token
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	String getCardToken();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column payment.card_token
	 *
	 * @param cardToken the value for payment.card_token
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setCardToken(String cardToken);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column payment.card_last4
	 *
	 * @return the value of payment.card_last4
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	String getCardLast4();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column payment.card_last4
	 *
	 * @param cardLast4 the value for payment.card_last4
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setCardLast4(String cardLast4);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column payment.amount
	 *
	 * @return the value of payment.amount
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	BigDecimal getAmount();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column payment.amount
	 *
	 * @param amount the value for payment.amount
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setAmount(BigDecimal amount);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column payment.amount_refunded
	 *
	 * @return the value of payment.amount_refunded
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	BigDecimal getAmountRefunded();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column payment.amount_refunded
	 *
	 * @param amountRefunded the value for payment.amount_refunded
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setAmountRefunded(BigDecimal amountRefunded);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column payment.processor_ref
	 *
	 * @return the value of payment.processor_ref
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	String getProcessorRef();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column payment.processor_ref
	 *
	 * @param processorRef the value for payment.processor_ref
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setProcessorRef(String processorRef);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column payment.processor_error
	 *
	 * @return the value of payment.processor_error
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	String getProcessorError();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column payment.processor_error
	 *
	 * @param processorError the value for payment.processor_error
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setProcessorError(String processorError);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column payment.processor_fee
	 *
	 * @return the value of payment.processor_fee
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	BigDecimal getProcessorFee();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column payment.processor_fee
	 *
	 * @param processorFee the value for payment.processor_fee
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setProcessorFee(BigDecimal processorFee);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column payment.paid
	 *
	 * @return the value of payment.paid
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	boolean isPaid();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column payment.paid
	 *
	 * @param paid the value for payment.paid
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setPaid(boolean paid);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column payment.refunded
	 *
	 * @return the value of payment.refunded
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	boolean isRefunded();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column payment.refunded
	 *
	 * @param refunded the value for payment.refunded
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setRefunded(boolean refunded);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column payment.disputed
	 *
	 * @return the value of payment.disputed
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	boolean isDisputed();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column payment.disputed
	 *
	 * @param disputed the value for payment.disputed
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setDisputed(boolean disputed);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column payment.failed
	 *
	 * @return the value of payment.failed
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	boolean isFailed();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column payment.failed
	 *
	 * @param failed the value for payment.failed
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setFailed(boolean failed);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column payment.created_date
	 *
	 * @return the value of payment.created_date
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	Date getCreatedDate();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column payment.created_date
	 *
	 * @param createdDate the value for payment.created_date
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setCreatedDate(Date createdDate);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column payment.paid_date
	 *
	 * @return the value of payment.paid_date
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	Date getPaidDate();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column payment.paid_date
	 *
	 * @param paidDate the value for payment.paid_date
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setPaidDate(Date paidDate);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column payment.disputed_date
	 *
	 * @return the value of payment.disputed_date
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	Date getDisputedDate();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column payment.disputed_date
	 *
	 * @param disputedDate the value for payment.disputed_date
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setDisputedDate(Date disputedDate);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column payment.refunded_date
	 *
	 * @return the value of payment.refunded_date
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	Date getRefundedDate();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column payment.refunded_date
	 *
	 * @param refundedDate the value for payment.refunded_date
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setRefundedDate(Date refundedDate);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column payment.failed_date
	 *
	 * @return the value of payment.failed_date
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	Date getFailedDate();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column payment.failed_date
	 *
	 * @param failedDate the value for payment.failed_date
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setFailedDate(Date failedDate);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column payment.last_updated
	 *
	 * @return the value of payment.last_updated
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	Date getUpdatedDate();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column payment.last_updated
	 *
	 * @param updatedDate the value for payment.last_updated
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setUpdatedDate(Date updatedDate);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column payment.processor_receipt
	 *
	 * @return the value of payment.processor_receipt
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	String getProcessorReceipt();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column payment.processor_receipt
	 *
	 * @param processorReceipt the value for payment.processor_receipt
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setProcessorReceipt(String processorReceipt);

}