package com.linuxtek.kona.app.sales.entity;

import java.math.BigDecimal;
import java.util.Date;

import com.linuxtek.kona.data.entity.KEntityObject;

public interface KPreOrder extends KEntityObject {

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column pre_order.id
	 *
	 * @return the value of pre_order.id
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	Long getId();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column pre_order.id
	 *
	 * @param id the value for pre_order.id
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setId(Long id);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column pre_order.uid
	 *
	 * @return the value of pre_order.uid
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	String getUid();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column pre_order.uid
	 *
	 * @param uid the value for pre_order.uid
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setUid(String uid);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column pre_order.app_id
	 *
	 * @return the value of pre_order.app_id
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	Long getAppId();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column pre_order.app_id
	 *
	 * @param appId the value for pre_order.app_id
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setAppId(Long appId);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column pre_order.partner_id
	 *
	 * @return the value of pre_order.partner_id
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	Long getPartnerId();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column pre_order.partner_id
	 *
	 * @param partnerId the value for pre_order.partner_id
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setPartnerId(Long partnerId);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column pre_order.product_id
	 *
	 * @return the value of pre_order.product_id
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	Long getProductId();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column pre_order.product_id
	 *
	 * @param productId the value for pre_order.product_id
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setProductId(Long productId);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column pre_order.campaign_id
	 *
	 * @return the value of pre_order.campaign_id
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	Long getCampaignId();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column pre_order.campaign_id
	 *
	 * @param campaignId the value for pre_order.campaign_id
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setCampaignId(Long campaignId);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column pre_order.payment_id
	 *
	 * @return the value of pre_order.payment_id
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	Long getPaymentId();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column pre_order.payment_id
	 *
	 * @param paymentId the value for pre_order.payment_id
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setPaymentId(Long paymentId);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column pre_order.ref_app_id
	 *
	 * @return the value of pre_order.ref_app_id
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	Long getRefAppId();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column pre_order.ref_app_id
	 *
	 * @param refAppId the value for pre_order.ref_app_id
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setRefAppId(Long refAppId);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column pre_order.referred_by_user_id
	 *
	 * @return the value of pre_order.referred_by_user_id
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	Long getReferredByUserId();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column pre_order.referred_by_user_id
	 *
	 * @param referredByUserId the value for pre_order.referred_by_user_id
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setReferredByUserId(Long referredByUserId);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column pre_order.amount
	 *
	 * @return the value of pre_order.amount
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	BigDecimal getAmount();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column pre_order.amount
	 *
	 * @param amount the value for pre_order.amount
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setAmount(BigDecimal amount);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column pre_order.reconciled
	 *
	 * @return the value of pre_order.reconciled
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	boolean isReconciled();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column pre_order.reconciled
	 *
	 * @param reconciled the value for pre_order.reconciled
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setReconciled(boolean reconciled);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column pre_order.proxy_payment
	 *
	 * @return the value of pre_order.proxy_payment
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	boolean isProxyPayment();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column pre_order.proxy_payment
	 *
	 * @param proxyPayment the value for pre_order.proxy_payment
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setProxyPayment(boolean proxyPayment);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column pre_order.processor
	 *
	 * @return the value of pre_order.processor
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	String getProcessor();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column pre_order.processor
	 *
	 * @param processor the value for pre_order.processor
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setProcessor(String processor);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column pre_order.payment_description
	 *
	 * @return the value of pre_order.payment_description
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	String getPaymentDescription();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column pre_order.payment_description
	 *
	 * @param paymentDescription the value for pre_order.payment_description
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setPaymentDescription(String paymentDescription);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column pre_order.payment_token
	 *
	 * @return the value of pre_order.payment_token
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	String getPaymentToken();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column pre_order.payment_token
	 *
	 * @param paymentToken the value for pre_order.payment_token
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setPaymentToken(String paymentToken);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column pre_order.payment_card_last4
	 *
	 * @return the value of pre_order.payment_card_last4
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	String getPaymentCardLast4();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column pre_order.payment_card_last4
	 *
	 * @param paymentCardLast4 the value for pre_order.payment_card_last4
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setPaymentCardLast4(String paymentCardLast4);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column pre_order.payment_ref
	 *
	 * @return the value of pre_order.payment_ref
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	String getPaymentRef();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column pre_order.payment_ref
	 *
	 * @param paymentRef the value for pre_order.payment_ref
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setPaymentRef(String paymentRef);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column pre_order.first_name
	 *
	 * @return the value of pre_order.first_name
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	String getFirstName();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column pre_order.first_name
	 *
	 * @param firstName the value for pre_order.first_name
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setFirstName(String firstName);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column pre_order.last_name
	 *
	 * @return the value of pre_order.last_name
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	String getLastName();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column pre_order.last_name
	 *
	 * @param lastName the value for pre_order.last_name
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setLastName(String lastName);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column pre_order.email
	 *
	 * @return the value of pre_order.email
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	String getEmail();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column pre_order.email
	 *
	 * @param email the value for pre_order.email
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setEmail(String email);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column pre_order.mobile_number
	 *
	 * @return the value of pre_order.mobile_number
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	String getMobileNumber();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column pre_order.mobile_number
	 *
	 * @param mobileNumber the value for pre_order.mobile_number
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setMobileNumber(String mobileNumber);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column pre_order.shipping_address1
	 *
	 * @return the value of pre_order.shipping_address1
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	String getShippingAddress1();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column pre_order.shipping_address1
	 *
	 * @param shippingAddress1 the value for pre_order.shipping_address1
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setShippingAddress1(String shippingAddress1);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column pre_order.shipping_address2
	 *
	 * @return the value of pre_order.shipping_address2
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	String getShippingAddress2();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column pre_order.shipping_address2
	 *
	 * @param shippingAddress2 the value for pre_order.shipping_address2
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setShippingAddress2(String shippingAddress2);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column pre_order.shipping_city
	 *
	 * @return the value of pre_order.shipping_city
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	String getShippingCity();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column pre_order.shipping_city
	 *
	 * @param shippingCity the value for pre_order.shipping_city
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setShippingCity(String shippingCity);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column pre_order.shipping_state
	 *
	 * @return the value of pre_order.shipping_state
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	String getShippingState();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column pre_order.shipping_state
	 *
	 * @param shippingState the value for pre_order.shipping_state
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setShippingState(String shippingState);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column pre_order.shipping_postal_code
	 *
	 * @return the value of pre_order.shipping_postal_code
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	String getShippingPostalCode();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column pre_order.shipping_postal_code
	 *
	 * @param shippingPostalCode the value for pre_order.shipping_postal_code
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setShippingPostalCode(String shippingPostalCode);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column pre_order.shipping_country
	 *
	 * @return the value of pre_order.shipping_country
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	String getShippingCountry();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column pre_order.shipping_country
	 *
	 * @param shippingCountry the value for pre_order.shipping_country
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setShippingCountry(String shippingCountry);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column pre_order.notes
	 *
	 * @return the value of pre_order.notes
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	String getNotes();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column pre_order.notes
	 *
	 * @param notes the value for pre_order.notes
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setNotes(String notes);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column pre_order.hostname
	 *
	 * @return the value of pre_order.hostname
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	String getHostname();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column pre_order.hostname
	 *
	 * @param hostname the value for pre_order.hostname
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setHostname(String hostname);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column pre_order.browser
	 *
	 * @return the value of pre_order.browser
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	String getBrowser();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column pre_order.browser
	 *
	 * @param browser the value for pre_order.browser
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setBrowser(String browser);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column pre_order.created_date
	 *
	 * @return the value of pre_order.created_date
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	Date getCreatedDate();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column pre_order.created_date
	 *
	 * @param createdDate the value for pre_order.created_date
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setCreatedDate(Date createdDate);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column pre_order.shipped_date
	 *
	 * @return the value of pre_order.shipped_date
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	Date getShippedDate();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column pre_order.shipped_date
	 *
	 * @param shippedDate the value for pre_order.shipped_date
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setShippedDate(Date shippedDate);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column pre_order.last_updated
	 *
	 * @return the value of pre_order.last_updated
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	Date getLastUpdated();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column pre_order.last_updated
	 *
	 * @param lastUpdated the value for pre_order.last_updated
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setLastUpdated(Date lastUpdated);

}