package com.linuxtek.kona.app.sales.entity;

import java.math.BigDecimal;
import java.util.Date;

import com.linuxtek.kona.data.entity.KEntityObject;

public interface KPromo extends KEntityObject {

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column promo.id
	 *
	 * @return the value of promo.id
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	Long getId();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column promo.id
	 *
	 * @param id the value for promo.id
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setId(Long id);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column promo.app_id
	 *
	 * @return the value of promo.app_id
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	Long getAppId();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column promo.app_id
	 *
	 * @param appId the value for promo.app_id
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setAppId(Long appId);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column promo.product_id
	 *
	 * @return the value of promo.product_id
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	Long getProductId();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column promo.product_id
	 *
	 * @param productId the value for promo.product_id
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setProductId(Long productId);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column promo.name
	 *
	 * @return the value of promo.name
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	String getName();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column promo.name
	 *
	 * @param name the value for promo.name
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setName(String name);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column promo.display_name
	 *
	 * @return the value of promo.display_name
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	String getDisplayName();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column promo.display_name
	 *
	 * @param displayName the value for promo.display_name
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setDisplayName(String displayName);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column promo.description
	 *
	 * @return the value of promo.description
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	String getDescription();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column promo.description
	 *
	 * @param description the value for promo.description
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setDescription(String description);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column promo.enabled
	 *
	 * @return the value of promo.enabled
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	boolean isEnabled();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column promo.enabled
	 *
	 * @param enabled the value for promo.enabled
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setEnabled(boolean enabled);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column promo.visible
	 *
	 * @return the value of promo.visible
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	boolean isVisible();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column promo.visible
	 *
	 * @param visible the value for promo.visible
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setVisible(boolean visible);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column promo.signup_default
	 *
	 * @return the value of promo.signup_default
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	boolean isSignupDefault();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column promo.signup_default
	 *
	 * @param signupDefault the value for promo.signup_default
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setSignupDefault(boolean signupDefault);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column promo.created_date
	 *
	 * @return the value of promo.created_date
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	Date getCreatedDate();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column promo.created_date
	 *
	 * @param createdDate the value for promo.created_date
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setCreatedDate(Date createdDate);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column promo.start_date
	 *
	 * @return the value of promo.start_date
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	Date getStartDate();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column promo.start_date
	 *
	 * @param startDate the value for promo.start_date
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setStartDate(Date startDate);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column promo.end_date
	 *
	 * @return the value of promo.end_date
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	Date getEndDate();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column promo.end_date
	 *
	 * @param endDate the value for promo.end_date
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setEndDate(Date endDate);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column promo.use_count
	 *
	 * @return the value of promo.use_count
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	Integer getUseCount();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column promo.use_count
	 *
	 * @param useCount the value for promo.use_count
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setUseCount(Integer useCount);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column promo.use_per_account
	 *
	 * @return the value of promo.use_per_account
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	Integer getUsePerAccount();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column promo.use_per_account
	 *
	 * @param usePerAccount the value for promo.use_per_account
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setUsePerAccount(Integer usePerAccount);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column promo.max_use_count
	 *
	 * @return the value of promo.max_use_count
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	Integer getMaxUseCount();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column promo.max_use_count
	 *
	 * @param maxUseCount the value for promo.max_use_count
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setMaxUseCount(Integer maxUseCount);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column promo.discount_pct
	 *
	 * @return the value of promo.discount_pct
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	Integer getDiscountPct();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column promo.discount_pct
	 *
	 * @param discountPct the value for promo.discount_pct
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setDiscountPct(Integer discountPct);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column promo.discount_amount
	 *
	 * @return the value of promo.discount_amount
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	BigDecimal getDiscountAmount();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column promo.discount_amount
	 *
	 * @param discountAmount the value for promo.discount_amount
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setDiscountAmount(BigDecimal discountAmount);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column promo.setup_fee
	 *
	 * @return the value of promo.setup_fee
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	BigDecimal getSetupFee();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column promo.setup_fee
	 *
	 * @param setupFee the value for promo.setup_fee
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setSetupFee(BigDecimal setupFee);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column promo.trial_days
	 *
	 * @return the value of promo.trial_days
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	Integer getTrialDays();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column promo.trial_days
	 *
	 * @param trialDays the value for promo.trial_days
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setTrialDays(Integer trialDays);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column promo.subscription_days
	 *
	 * @return the value of promo.subscription_days
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	Integer getSubscriptionDays();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column promo.subscription_days
	 *
	 * @param subscriptionDays the value for promo.subscription_days
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setSubscriptionDays(Integer subscriptionDays);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column promo.validation_rule
	 *
	 * @return the value of promo.validation_rule
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	String getValidationRule();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column promo.validation_rule
	 *
	 * @param validationRule the value for promo.validation_rule
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setValidationRule(String validationRule);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column promo.last_updated
	 *
	 * @return the value of promo.last_updated
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	Date getLastUpdated();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column promo.last_updated
	 *
	 * @param lastUpdated the value for promo.last_updated
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setLastUpdated(Date lastUpdated);

}