package com.linuxtek.kona.app.sales.entity;

import java.math.BigDecimal;
import java.util.Date;

import com.linuxtek.kona.data.entity.KEntityObject;

public interface KProduct extends KEntityObject {

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column product.id
	 *
	 * @return the value of product.id
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	Long getId();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column product.id
	 *
	 * @param id the value for product.id
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setId(Long id);

    String getUid();
    void setUid(String uid);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column product.app_id
	 *
	 * @return the value of product.app_id
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	Long getAppId();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column product.app_id
	 *
	 * @param appId the value for product.app_id
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setAppId(Long appId);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column product.name
	 *
	 * @return the value of product.name
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	String getName();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column product.name
	 *
	 * @param name the value for product.name
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setName(String name);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column product.display_name
	 *
	 * @return the value of product.display_name
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	String getDisplayName();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column product.display_name
	 *
	 * @param displayName the value for product.display_name
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setDisplayName(String displayName);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column product.display_order
	 *
	 * @return the value of product.display_order
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	Integer getDisplayOrder();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column product.display_order
	 *
	 * @param displayOrder the value for product.display_order
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setDisplayOrder(Integer displayOrder);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column product.description
	 *
	 * @return the value of product.description
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	String getDescription();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column product.description
	 *
	 * @param description the value for product.description
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setDescription(String description);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column product.price
	 *
	 * @return the value of product.price
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	BigDecimal getPrice();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column product.price
	 *
	 * @param price the value for product.price
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setPrice(BigDecimal price);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column product.setup_fee
	 *
	 * @return the value of product.setup_fee
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	BigDecimal getSetupFee();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column product.setup_fee
	 *
	 * @param setupFee the value for product.setup_fee
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setSetupFee(BigDecimal setupFee);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column product.trial_days
	 *
	 * @return the value of product.trial_days
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	Integer getTrialDays();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column product.trial_days
	 *
	 * @param trialDays the value for product.trial_days
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setTrialDays(Integer trialDays);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column product.subscription
	 *
	 * @return the value of product.subscription
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	boolean isSubscription();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column product.subscription
	 *
	 * @param subscription the value for product.subscription
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setSubscription(boolean subscription);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column product.subscription_days
	 *
	 * @return the value of product.subscription_days
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	Integer getSubscriptionDays();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column product.subscription_days
	 *
	 * @param subscriptionDays the value for product.subscription_days
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setSubscriptionDays(Integer subscriptionDays);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column product.support_type
	 *
	 * @return the value of product.support_type
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	String getSupportType();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column product.support_type
	 *
	 * @param supportType the value for product.support_type
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setSupportType(String supportType);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column product.active
	 *
	 * @return the value of product.active
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	boolean isActive();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column product.active
	 *
	 * @param active the value for product.active
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setActive(boolean active);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column product.created_date
	 *
	 * @return the value of product.created_date
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	Date getCreatedDate();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column product.created_date
	 *
	 * @param createdDate the value for product.created_date
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setCreatedDate(Date createdDate);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column product.last_updated
	 *
	 * @return the value of product.last_updated
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	Date getUpdatedDate();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column product.last_updated
	 *
	 * @param updatedDate the value for product.last_updated
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setUpdatedDate(Date updatedDate);

}
