package com.linuxtek.kona.app.sales.entity;

import java.util.Date;

import com.linuxtek.kona.data.entity.KEntityObject;

public interface KPurchase extends KEntityObject {

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column product_purchase.id
	 *
	 * @return the value of product_purchase.id
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	Long getId();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column product_purchase.id
	 *
	 * @param id the value for product_purchase.id
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setId(Long id);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column product_purchase.parent_id
	 *
	 * @return the value of product_purchase.parent_id
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	Long getParentId();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column product_purchase.parent_id
	 *
	 * @param parentId the value for product_purchase.parent_id
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setParentId(Long parentId);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column product_purchase.account_id
	 *
	 * @return the value of product_purchase.account_id
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	Long getAccountId();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column product_purchase.account_id
	 *
	 * @param accountId the value for product_purchase.account_id
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setAccountId(Long accountId);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column product_purchase.user_id
	 *
	 * @return the value of product_purchase.user_id
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	Long getUserId();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column product_purchase.user_id
	 *
	 * @param userId the value for product_purchase.user_id
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setUserId(Long userId);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column product_purchase.product_id
	 *
	 * @return the value of product_purchase.product_id
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	Long getProductId();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column product_purchase.product_id
	 *
	 * @param productId the value for product_purchase.product_id
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setProductId(Long productId);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column product_purchase.app_id
	 *
	 * @return the value of product_purchase.app_id
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	Long getAppId();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column product_purchase.app_id
	 *
	 * @param appId the value for product_purchase.app_id
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setAppId(Long appId);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column product_purchase.promo_id
	 *
	 * @return the value of product_purchase.promo_id
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	Long getPromoId();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column product_purchase.promo_id
	 *
	 * @param promoId the value for product_purchase.promo_id
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setPromoId(Long promoId);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column product_purchase.partner_id
	 *
	 * @return the value of product_purchase.partner_id
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	Long getPartnerId();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column product_purchase.partner_id
	 *
	 * @param partnerId the value for product_purchase.partner_id
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setPartnerId(Long partnerId);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column product_purchase.campaign_id
	 *
	 * @return the value of product_purchase.campaign_id
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	Long getCampaignId();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column product_purchase.campaign_id
	 *
	 * @param campaignId the value for product_purchase.campaign_id
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setCampaignId(Long campaignId);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column product_purchase.payment_type_id
	 *
	 * @return the value of product_purchase.payment_type_id
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	Long getPaymentTypeId();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column product_purchase.payment_type_id
	 *
	 * @param paymentTypeId the value for product_purchase.payment_type_id
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setPaymentTypeId(Long paymentTypeId);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column product_purchase.kind
	 *
	 * @return the value of product_purchase.kind
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	String getKind();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column product_purchase.kind
	 *
	 * @param kind the value for product_purchase.kind
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setKind(String kind);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column product_purchase.invoice_no
	 *
	 * @return the value of product_purchase.invoice_no
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	String getInvoiceNo();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column product_purchase.invoice_no
	 *
	 * @param invoiceNo the value for product_purchase.invoice_no
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setInvoiceNo(String invoiceNo);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column product_purchase.auto_renew
	 *
	 * @return the value of product_purchase.auto_renew
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	boolean isAutoRenew();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column product_purchase.auto_renew
	 *
	 * @param autoRenew the value for product_purchase.auto_renew
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setAutoRenew(boolean autoRenew);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column product_purchase.enabled
	 *
	 * @return the value of product_purchase.enabled
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	boolean isEnabled();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column product_purchase.enabled
	 *
	 * @param enabled the value for product_purchase.enabled
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setEnabled(boolean enabled);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column product_purchase.created_date
	 *
	 * @return the value of product_purchase.created_date
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	Date getCreatedDate();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column product_purchase.created_date
	 *
	 * @param createdDate the value for product_purchase.created_date
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setCreatedDate(Date createdDate);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column product_purchase.expiration_date
	 *
	 * @return the value of product_purchase.expiration_date
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	Date getExpirationDate();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column product_purchase.expiration_date
	 *
	 * @param expirationDate the value for product_purchase.expiration_date
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setExpirationDate(Date expirationDate);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column product_purchase.last_updated
	 *
	 * @return the value of product_purchase.last_updated
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	Date getLastUpdated();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column product_purchase.last_updated
	 *
	 * @param lastUpdated the value for product_purchase.last_updated
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setLastUpdated(Date lastUpdated);

}
