package com.linuxtek.kona.app.sales.entity;

import java.util.Date;

import com.linuxtek.kona.data.entity.KEntityObject;

public interface KSalesLead extends KEntityObject {

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column sales_lead.id
	 *
	 * @return the value of sales_lead.id
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	Long getId();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column sales_lead.id
	 *
	 * @param id the value for sales_lead.id
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setId(Long id);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column sales_lead.uid
	 *
	 * @return the value of sales_lead.uid
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	String getUid();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column sales_lead.uid
	 *
	 * @param uid the value for sales_lead.uid
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setUid(String uid);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column sales_lead.app_id
	 *
	 * @return the value of sales_lead.app_id
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	Long getAppId();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column sales_lead.app_id
	 *
	 * @param appId the value for sales_lead.app_id
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setAppId(Long appId);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column sales_lead.ref_app_id
	 *
	 * @return the value of sales_lead.ref_app_id
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	Long getRefAppId();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column sales_lead.ref_app_id
	 *
	 * @param refAppId the value for sales_lead.ref_app_id
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setRefAppId(Long refAppId);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column sales_lead.first_name
	 *
	 * @return the value of sales_lead.first_name
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	String getFirstName();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column sales_lead.first_name
	 *
	 * @param firstName the value for sales_lead.first_name
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setFirstName(String firstName);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column sales_lead.last_name
	 *
	 * @return the value of sales_lead.last_name
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	String getLastName();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column sales_lead.last_name
	 *
	 * @param lastName the value for sales_lead.last_name
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setLastName(String lastName);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column sales_lead.phone
	 *
	 * @return the value of sales_lead.phone
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	String getPhone();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column sales_lead.phone
	 *
	 * @param phone the value for sales_lead.phone
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setPhone(String phone);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column sales_lead.email
	 *
	 * @return the value of sales_lead.email
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	String getEmail();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column sales_lead.email
	 *
	 * @param email the value for sales_lead.email
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setEmail(String email);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column sales_lead.mobile_number
	 *
	 * @return the value of sales_lead.mobile_number
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	String getMobileNumber();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column sales_lead.mobile_number
	 *
	 * @param mobileNumber the value for sales_lead.mobile_number
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setMobileNumber(String mobileNumber);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column sales_lead.comment
	 *
	 * @return the value of sales_lead.comment
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	String getComment();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column sales_lead.comment
	 *
	 * @param comment the value for sales_lead.comment
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setComment(String comment);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column sales_lead.twitterUsername
	 *
	 * @return the value of sales_lead.twitterUsername
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	String getTwitterusername();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column sales_lead.twitterUsername
	 *
	 * @param twitterusername the value for sales_lead.twitterUsername
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setTwitterusername(String twitterusername);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column sales_lead.facebookUsername
	 *
	 * @return the value of sales_lead.facebookUsername
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	String getFacebookusername();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column sales_lead.facebookUsername
	 *
	 * @param facebookusername the value for sales_lead.facebookUsername
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setFacebookusername(String facebookusername);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column sales_lead.referred_by_user_id
	 *
	 * @return the value of sales_lead.referred_by_user_id
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	Long getReferredByUserId();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column sales_lead.referred_by_user_id
	 *
	 * @param referredByUserId the value for sales_lead.referred_by_user_id
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setReferredByUserId(Long referredByUserId);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column sales_lead.campaign_id
	 *
	 * @return the value of sales_lead.campaign_id
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	Long getCampaignId();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column sales_lead.campaign_id
	 *
	 * @param campaignId the value for sales_lead.campaign_id
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setCampaignId(Long campaignId);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column sales_lead.channel
	 *
	 * @return the value of sales_lead.channel
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	String getChannel();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column sales_lead.channel
	 *
	 * @param channel the value for sales_lead.channel
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setChannel(String channel);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column sales_lead.interests
	 *
	 * @return the value of sales_lead.interests
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	String getInterests();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column sales_lead.interests
	 *
	 * @param interests the value for sales_lead.interests
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setInterests(String interests);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column sales_lead.hostname
	 *
	 * @return the value of sales_lead.hostname
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	String getHostname();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column sales_lead.hostname
	 *
	 * @param hostname the value for sales_lead.hostname
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setHostname(String hostname);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column sales_lead.browser
	 *
	 * @return the value of sales_lead.browser
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	String getBrowser();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column sales_lead.browser
	 *
	 * @param browser the value for sales_lead.browser
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setBrowser(String browser);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column sales_lead.created_date
	 *
	 * @return the value of sales_lead.created_date
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	Date getCreatedDate();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column sales_lead.created_date
	 *
	 * @param createdDate the value for sales_lead.created_date
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setCreatedDate(Date createdDate);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column sales_lead.last_updated
	 *
	 * @return the value of sales_lead.last_updated
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	Date getUpdatedDate();

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column sales_lead.last_updated
	 *
	 * @param updatedDate the value for sales_lead.last_updated
	 *
	 * @mbggenerated Thu Apr 07 17:04:20 MDT 2016
	 */
	void setUpdatedDate(Date updatedDate);

}